### PR TITLE
chore: updates typescript config to allow resolving JSON modules.

### PR DESCRIPTION
**Pull request by driskull**
chore: updates typescript config to allow resolving JSON modules. #2367

### CODE REVIEW

**Comment by jcfranco** [comment]
Can you give some context on what this addresses? Can't infer that from the title/description.

**Comment by driskull** [comment]
Updated

**Comment by jcfranco** [comment]
I'm sorry, but I still don't know what this change will address. 🤔

**Comment by driskull** [comment]
@jcfranco This will fix the typescript module errors in 'date.spec.ts' as shown below.

image

**Comment by driskull** [comment]
related to https://github.com/Esri/calcite-components/pull/2368

**Comment by jcfranco** [comment]
Gotcha. Thanks for the info. This looks like a nice little improvement!

**Review by jcfranco — APPROVED** [review]
👍🏼

**Pull request merged**
