### PR TITLE
fix(input): set value to empty string instead of null or undefined

### PR DESCRIPTION
**Pull request by benelan**
**Related Issue:** #3627

## Summary
- The PR linked above moved to use an empty string for the value instead of `null`. I made the same change for pasting invalid numbers.

### CODE REVIEW

**Comment by benelan** [comment]
@jcfranco / @eriklharper, should this one be an empty string too?
https://github.com/Esri/calcite-components/blob/6a9756c4f3a0840c0c22195b2287aa487c8f1c1f/src/components/calcite-input/calcite-input.tsx#L291

**Comment by eriklharper** [comment]
> @jcfranco / @eriklharper, should this one be an empty string too?
> 
> https://github.com/Esri/calcite-components/blob/6a9756c4f3a0840c0c22195b2287aa487c8f1c1f/src/components/calcite-input/calcite-input.tsx#L291

I would say yes, since the intention with this PR is to use "" as the empty value.  This is how the native input behaves.

**Review by eriklharper — APPROVED** [review]
LGTM once you change the line you mentioned from undefined to empty string.

**Review by jcfranco — COMMENTED** [review]
Thanks for fixing this! :muscle:

**Pull request merged**
