### PR TITLE
docs: update changelog's breaking changes.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #

## Summary

docs: update changelog's breaking changes.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
👍

**Comment by jcfranco** [comment]
@benelan @geospatialem These will get overridden by the changelog-generating script in the next release, right? What would you suggest to make sure we apply these updates then?

**Comment by benelan** [comment]
I think so, but I'm not 100% sure. I made a note for myself to check during the next release. If it is overwritten I'll fix it and look into fixing the script

**Comment by driskull** [comment]
Yeah ideally the script wouldn't overwrite any modified entries.

**Comment by driskull** [comment]
Looks like the script did overwrite it. We'll need to figure out a way to keep modified changes somehow.

**Pull request merged**
