### PR TITLE
test(card): updated card demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2626 

## Summary
- updated _calcite-card_ demo page

### CODE REVIEW

**Comment by bstifle** [comment]
pretty good!

can we change the label on this one? "No buttons, selectable"

image

**Review by julio8a — APPROVED** [review]

**Review by bstifle — APPROVED** [review]
ship

**Comment by julio8a** [comment]
you need fo fix the merge conflicts on this PR

**Comment by julio8a** [comment]
nice! thinks one is good to merge! Great job @ManahariDahal

**Pull request merged**
