### PR TITLE
feat(accordion): deprecate iconPosition and add support for alignment prop

### PR DESCRIPTION
**Pull request by anveshmekala**
**Related Issue:**  #4688 

## Summary

This will deprecate `iconPosition` prop for `calcite-accordion` and devs have to use the `alignment` prop instead.

### CODE REVIEW

**Comment by driskull** [comment]
@anveshmekala do you know what issue this is for? Seems like it links to a PR right now.

I'm wondering if `alignment` is too vague. It doesn't specify that it positions the icon in a different place. I'm not sure `alignment` is the right word for this. Is there some discussion regarding the name?

**Comment by anveshmekala** [comment]
> @anveshmekala do you know what issue this is for? Seems like it links to a PR right now.
> 
> I'm wondering if `alignment` is too vague. It doesn't specify that it positions the icon in a different place. I'm not sure `alignment` is the right word for this. Is there some discussion regarding the name?

Oops, mis-spelled 4688 for 4668. Corrected it now. 
There has been a discussion regarding the naming in teams.  Open to suggestions in terms of name. 

cc @macandcheese

**Review by driskull — COMMENTED** [review]
I think we decided to keep iconPosition right?

**Comment by anveshmekala** [comment]
Closing this PR as we agreed to keep `iconPosition` & `iconType` prop for `accordion`.

**Pull request closed without merging**
