### PR TITLE
chore(storybook): streamline storybook setup

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This PR updates our Storybook setup, so that it can properly process doc-specific components (e.g., `.storybook/utils.tsx#globalDocsPage`). See https://storybook.js.org/docs/html/writing-docs/docs-page#with-a-custom-component for more info.

This should also help bump TypeScript without any additional changes to the configuration.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
Nice! so my PR can remove the styling to hide additional H1s right?

**Comment by jcfranco** [comment]
@driskull Yeah, I think you can revert anything that isn't a dependency bump. 🧹

**Comment by driskull** [comment]
@jcfranco can you verify bumping typescript works?

**Comment by jcfranco** [comment]
I tested w/ TS 4.3.5. Works smooth like buttah. 🧈

**Comment by driskull** [comment]
awesome!

**Comment by jcfranco** [comment]
Failing test is unrelated. Merging!

**Pull request merged**
