### PR TITLE
refactor(calcite-combobox): scale L updates

### PR DESCRIPTION
**Pull request by bpatterson88**
**Related Issue:** #2041 

## Summary
- Updated padding to match Figma
- Changed icons to S when combobox scale is L
- Added some examples to the demo page

### CODE REVIEW

**Comment by bpatterson88** [comment]
- Updated single select sizes to 24/32/44
- Updated select menus to better match size of inputs. Note that the select menu item heights aren't perfect (35px instead of 32px on M, 46px instead of 44px on L) because I'm using the wrapping line-height since the labels could potentially wrap.

**Review by caripizza — APPROVED** [review]
These changes look great to me based on Figma, and thanks for adding the additional demos @bpatterson88. 👍 
(I know you've been working with @bstifle so I'll make sure he has eyes on this too on Monday when he's back.)

**Comment by macandcheese** [comment]
Chatted with @bpatterson88 on this - let’s make sure these items can line wrap without issue, that will happen often with long string values, especially combined with an icon.

**Comment by bstifle** [comment]
this is looking really good ben!!!!

**Review by bstifle — APPROVED** [review]

**Comment by bstifle** [comment]
Ok! looks like single select has incorrect left/right padding.

Small should be 8, Medium 12, large 16

image
image
image

**Comment by bpatterson88** [comment]
@bstifle Updated the left/right padding

**Pull request merged**
