### PR TITLE
chore(card): rename select event and remove el from event detail

### PR DESCRIPTION
**Pull request by asangma**
@macandcheese could use some guidance on the event detail type part.

### CODE REVIEW

**Comment by macandcheese** [comment]
Looks good, although if selected is available on the target as an attribute perhaps that's not needed either?

**Comment by asangma** [comment]
@macandcheese That's what I was thinking. :)

**Comment by asangma** [comment]
Thanks @driskull!

**Comment by asangma** [comment]
Resolves #459

**Pull request merged**
