### PR TITLE
docs(template): provide context for the repro samples

### PR DESCRIPTION
**Pull request by benelan**
**Related Issue:** NA

## Summary
- Provide context for the repro samples we provide in the issue templates
- Change the JSBin to use `next`, it was still at `beta.64` 
    - Should it be `next` or `latest`? I think having it as `next` can help prevent unnecessary issues by having people test the unreleased changes.

### CODE REVIEW

**Review by driskull — APPROVED** [review]

**Review by jcfranco — APPROVED** [review]
Nice!

**Comment by jcfranco** [comment]
> Should it be `next` or `latest`

Let's stick to `latest` since `next` may not be stable in some instances.

**Pull request merged**
