### PR TITLE
chore: getAttributes() utility helper to spread attributes 

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1538

## Summary

chore: getAttributes() utility helper to spread attributes

@macandcheese could we change from a blockList to allowList on the attributes to pass down?

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]

**Review by jcfranco — APPROVED** [review]
👍 

Nitpick: shouldn't this be a `refactor`-type commit?

**Comment by driskull** [comment]
> Nitpick: shouldn't this be a refactor-type commit?

Mah bad. 😞

**Comment by driskull** [comment]
I'd prefer this to use a `allowList` instead if possible, but I think whoever works on these components would need to figure out which attributes are allowed.

Currently, if someone adds "my-crazy-attribute" it will then pass that to the internals of the component which could be bad.

It might even have some security concerns. 🤷 

cc @macandcheese @eriklharper

**Comment by driskull** [comment]
Can someone take this PR over and invert the logic so that only allowed attributes get though?

**Comment by driskull** [comment]
I will merge and create an issue for refactoring.

**Pull request merged**
