### PR TITLE
refactor(dropdown-group): tailwindify

### PR DESCRIPTION
**Pull request by julio8a**
Supports #1500

### CODE REVIEW

**Comment by julio8a** [comment]
Main change here is the border color (match inputs and other for accessibility)

**Review by paulcpederson — CHANGES_REQUESTED** [review]
Need to fix the group border.
Screen Shot 2021-03-22 at 9 59 56 AM

**Comment by julio8a** [comment]
fixed

**Review by jrowlingson — APPROVED** [review]

**Comment by julio8a** [comment]
@paulcpederson, this one is ready for review.

**Comment by julio8a** [comment]
going to PR this with dropdown PR.

**Pull request closed without merging**
