### PR TITLE
build: Remove @types/autoprefixer and add postcss. #2697

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2697

## Summary

build: Remove @types/autoprefixer and add postcss. #2697

Update build to get latest postcss version compatible with autoprefixer.

### CODE REVIEW

**Comment by driskull** [comment]
Maybe this will fix the repo switching error we have been seeing. 🤷

**Comment by jcfranco** [comment]
From what I understand, I _think_ we only need to remove the deprecated `@types/autoprefixer` package (good catch, BTW). We only reference `postcss` from `@stencil/postcss` and the latest `autoprefixer` includes the types.

**Comment by driskull** [comment]
I tried that but the two weren't in sync. I think we need both.

**Comment by jcfranco** [comment]
> I tried that but the two weren't in sync. 

Can you expand on that? Did you get a warning or an error?

**Comment by driskull** [comment]
Yeah the issue was that the auto prefixer typings were not compatible with the version of postcss that stencil/postcss defines.

If we set the latest of both it works fine. That's why the plug-in error is shown

**Comment by jcfranco** [comment]
I think I see what's going on. `autoprefixer` has `postcss@^8.1.0` as a peer dependency. Since we don't have it as an explicit dependency, the one at the root of `node_modules` is the one used to dedupe the common version across other dependencies (`postcss@7.0.35`).

Thanks for fixing this one!

**Review by jcfranco — APPROVED** [review]
👍🏼

**Comment by jcfranco** [comment]
On a related note, we should probably look at adding other peer dependencies based on the post `npm install` warnings. NPM 7 is supposed to handle this automatically, but we can't upgrade until Node 15 gets into Active LTS status.

**Comment by driskull** [comment]
> On a related note, we should probably look at adding other peer dependencies based on the post npm install warnings. NPM 7 is supposed to handle this automatically, but we can't upgrade until Node 15 gets into Active LTS status.

👍 yeah

**Pull request merged**
