### PR TITLE
docs(dropdown): Update readme to show correct "placement" property

### PR DESCRIPTION
**Pull request by noahmulfinger**
**Related Issue:**  N/A

## Summary

Update the calcite-dropdown readme so it shows the correct "placement" property since it changed from "alignment" => "placement" recently and there are now more placement options.

### CODE REVIEW

**Comment by jcfranco** [comment]
Thanks for the contribution, @noahmulfinger! The docs are generated from the JSDoc on the source files. Could you update the prop's doc, run the build to update the readmes and update the PR?

Also, could you remove `see [interfaces.ts](./interfaces.ts)`? The readme is referenced in different contexts and the relative path won't apply in some cases.

**Comment by noahmulfinger** [comment]
@jcfranco Interesting, the only reference I see to the old property `alignment` is in the readme. The .tsx file and all the other files only reference `placement`.

**Comment by jcfranco** [comment]
@noahmulfinger Apologies for the late reply. Then the doc just needs regenerating. I'll submit a PR to update all of the READMEs.

**Comment by jcfranco** [comment]
@Esri/calcite-components-reviewers FYI, I unintentionally pushed the doc updates on master. 😅  

@noahmulfinger Could you check out the latest version?

**Comment by noahmulfinger** [comment]
@jcfranco Looks good, thanks!

**Pull request closed without merging**
