### PR TITLE
chore(switch): add switched to event detail

### PR DESCRIPTION
**Pull request by asangma**
#474 also asks to remove `change`, but I am not seeing it in der.

### CODE REVIEW

**Comment by driskull** [comment]
I removed `change` event already.

**Comment by asangma** [comment]
Thanks @driskull !

**Comment by paulcpederson** [comment]
@asangma can you add this to the changelog in a new section named `Unreleased`. It makes it a lot easier to cut releases when all the changes are already documented and ready. 

Also, may be good to add a check for this event detail to the switch tests. Something like:

```
expect(changeEvent).toHaveFirstReceivedEventDetail({ switched: true });
```

Can be added [here](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-switch/calcite-switch.e2e.ts#L81)

**Comment by asangma** [comment]
@paulcpederson roger that.

**Comment by asangma** [comment]
Did the stuff.

**Comment by paulcpederson** [comment]
NICE. 

tayne15

**Comment by asangma** [comment]
dancing-baby-finn

**Comment by bstifle** [comment]
oyster-smiling

**Pull request merged**
