### PR TITLE
fix(panel): removes default width-scale and lets panel default width to be 100%

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #1126

## Summary
Removes default width-scale.
Allows panel to be 100% by default.

cc @AdelheidF

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Nice! Before merging, could you add a test for the component prop defaults?

**Review by driskull — APPROVED** [review]
👍

**Comment by AdelheidF** [comment]
Could you fix the typo in the doc as well? It should say width instead of height. Thanks.

**Comment by asangma** [comment]
@jcfranco Will do.

**Comment by asangma** [comment]
@jcfranco Does that test update look right to you?

**Comment by jcfranco** [comment]
@asangma Yeah. If you want to simplify, you can use the `defaults` helper ([example](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-block/calcite-block.e2e.ts#L10-L20)).

**Comment by asangma** [comment]
Thanks @jcfranco. I had a feeling there was a thing like that. 

Will murgle once tests have passed.

**Pull request merged**
