### PR TITLE
feat(calcite-list-item-group): Add support for grouping list items

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2350

## Summary

feat(calcite-list-item-group): Add support for grouping list items. #2350

### CODE REVIEW

**Comment by bstifle** [comment]
@driskull looks like the 2px margin was removed between the label and description.

Can we get that back in?

**Comment by driskull** [comment]
Can you updated it @bstifle? I'm not really sure on the styles.

**Comment by driskull** [comment]
> @driskull looks like the 2px margin was removed between the label and description.

@bstifle no margins were touched in this PR.

**Review by jcfranco — CHANGES_REQUESTED** [review]
Can you remove unrelated formatting changes from this?

**Comment by driskull** [comment]
> Can you remove unrelated formatting changes from this?

Yeah i'm not sure how that happened. I didn't run prettier locally.

**Pull request closed without merging**
