### PR TITLE
fix(input-date-picker): removes max-widths

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #1689 

## Summary
Removes max-widths.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Comment by paulcpederson** [comment]
@bstifle @julio8a can one of you take a gander at the screener diff and accept if you approve?

**Comment by asangma** [comment]
@paulcpederson @bstifle The Screener diff is coming from the reversion @julio8a just merged.

**Comment by asangma** [comment]
i.e. it's unrelated to this PR.

**Pull request merged**
