### PR TITLE
fix(date-picker): Selecting a day no longer activates previous day in certain time zones.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1863

## Summary

fix(date-picker): Selecting a day no longer activates previous day in certain time zones. 

Before converting a date to ISO format, `date.getTimezoneOffset() * 60000` is called to prevent this error from happening.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
LGTM! Before merging, can you add a test for this and revisit the commit title? The current text is describing the broken behavior.

**Comment by driskull** [comment]
@jcfranco I tried to add a test but failed. The test is dependent on setting the browser timezone in order to run correctly.

**Comment by driskull** [comment]
Updated title of PR.

**Comment by jcfranco** [comment]
> The test is dependent on setting the browser timezone in order to run correctly.

I see. If you haven't already, could you try [`page#emulateTimezone`](https://github.com/puppeteer/puppeteer/blob/v5.4.0/docs/api.md#pageemulatetimezonetimezoneid)? If this doesn't work, let's create an issue to see if we can come up with a consistent way of handling these tests.

**Comment by driskull** [comment]
Yeah that doesn't seem to work. It only seems to work if I set my system timezone. Emulating has no effect on the value.

Seems like i was testing it correctly  as seen here: https://github.com/puppeteer/puppeteer/pull/4949/files#diff-ffaaf2938a0892d9da34f14f80532475e9d3a5a337225c9d5a51e674c8302c41R174

Maybe they don't emulate `getTimezoneOffset`.

**Comment by driskull** [comment]
I think @paulcpederson should look at this one before we merge it. Can it wait till he's back?

**Comment by jcfranco** [comment]
@driskull Sure, let's hold off on this one then. BTW, thanks for making all of the changes and trying to get the test in! 💪🏼

**Comment by driskull** [comment]
@paulcpederson can you review?

**Comment by driskull** [comment]
@paulcpederson Will merge. Let me know if this needs further changes.

**Comment by paulcpederson** [comment]
Looks good, no changes needed.

**Pull request merged**
