### PR TITLE
fix(tile-select): ensure checked tile border is visible within tile-select group

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** #5389

## Summary

Setting z-index restores the outline.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Review by eriklharper — APPROVED** [review]
ah, THANK YOU Paul for fixing this!

**Comment by paulcpederson** [comment]
@benelan if a release is planned to be going out soon it would good to get this fix in. We use this component all over.

**Review by jcfranco — APPROVED** [review]
Thanks, @paulcpederson! Before merging, can you add a story to cover this scenario? See https://github.com/Esri/calcite-components/blob/master/conventions/Documentation.md#screenshot-test-only-stories for more info on this.

**Comment by paulcpederson** [comment]
@jcfranco this is covered by the normal simple story. Or really, any other story for tile select. 

The regression screenshot was accepted a while back, I guess whoever accepted it just didn't notice. I think is is due to the z-index rework.

**Comment by paulcpederson** [comment]
@eriklharper @driskull not sure what I have to do to get the screener test to finish but let me know how to fix this and merge...

**Comment by driskull** [comment]
@paulcpederson added the label. Screenshots should run now.

**Comment by benelan** [comment]
Dang, I'm sorry Paul. I thought this was already merged when I released the patch :/

Our next `beta` release is October 10th so it will make it into that one

**Comment by paulcpederson** [comment]
@benelan ok, merged in

**Pull request merged**
