### PR TITLE
refactor(modal)!: Renamed CSS variable

### PR DESCRIPTION
**Pull request by macandcheese**
BREAKING CHANGE: Removed `--calcite-modal-padding` CSS variable.

- Removed the `--calcite-modal-padding` CSS variable, use the `--calcite-modal-content-padding` CSS variable instead.

### CODE REVIEW

**Comment by macandcheese** [comment]
Also removes some unneeded duplicate CSS variables - keeps the `-internal` versions.

**Review by driskull — APPROVED** [review]
👍 Looks good. 

I modified the PR title to add the `!` since its a breaking change.

**Comment by macandcheese** [comment]
> 👍 Looks good.
> 
> I modified the PR title to add the `!` since its a breaking change.

Whoops, thanks @driskull

**Comment by macandcheese** [comment]
I think there's something wonky with the css processing and the fallback format, hold on: https://github.com/Esri/calcite-components/pull/6078/commits/cb223dcfd4a19579448bcbec7fa3efabefc78e71#diff-0b02b2fb1967f75b4eb428ae025550330bd7f48c7a8706a6c704552845698ec5R183

Looks like it requires explicit `padding-block` and `padding-inline`, let me fix...

**Pull request merged**
