### PR TITLE
updating license to Esri MLA

### PR DESCRIPTION
**Pull request by julio8a**

### CODE REVIEW

**Comment by paulcpederson** [comment]
@julio8a you should delete the `LICENSE` file as well as it has the text of the apache license in it

**Comment by julio8a** [comment]
Thanks @paulcpederson, file removed.

**Comment by paulcpederson** [comment]
@julio8a sorry one more thing, we should also update the `license` field in `package.json` https://github.com/Esri/calcite-components/blob/master/package.json#L77

I think the syntax for something that is copyrighted is to use `UNLICENSED`.

**Comment by julio8a** [comment]
Good catch, updated.

**Pull request merged**
