### PR TITLE
feat(color): allow hiding sections

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #763 

## Summary

This adds the following properties to hide sections:

* `hideHex` - hides hex input section
* `hideChannels` - hides RGB/HSV channels section
* `hideSaved` - hides saved colors section

**Note**: The color field/slider cannot be hidden as this is the main color selection part.

### CODE REVIEW

**Comment by jcfranco** [comment]
@bstifle mayhaps you could taketh a gander? 🙇‍♂️ 

**scale=l**

Screen Shot 2020-08-12 at 2 08 05 PM

**scale=m**

Screen Shot 2020-08-12 at 2 07 26 PM

**scale=s**

Screen Shot 2020-08-12 at 2 08 39 PM

**Comment by bstifle** [comment]
@jcfranco Heck yeah! Was just thinking about this, you read my mind. I'll check it out now

**Comment by bstifle** [comment]
@jcfranco 

ok so im just seeing this. looks like the padding gets messed up in this scenario.

image

**Comment by jcfranco** [comment]
Sorry, I forgot to push some changes. The screenshots are from the latest. Let me fix that.

**Comment by jcfranco** [comment]
Pushed!

**Comment by macandcheese** [comment]
Awesome! A few ultra annoying nitpicks (sorry 😬 ):

- RTL alignment seems a little off, the tabbed section should be pushed out to align with the text and hex input:
Slice

- The `margin:0 8px` on `delete-color` can be removed - it should be adjacent to the `add-button` with no space.

| Current  | Desired  |
|---|---|
| Screen Shot 2020-08-13 at 12 40 27 PM | Screen Shot 2020-08-13 at 12 40 23 PM |


- The add / remove buttons in dark theme should have `theme=dark` set on them so hover is more apparent.

| Current  | Desired  |
|---|---|
| Screen Shot 2020-08-13 at 12 38 42 PM | Screen Shot 2020-08-13 at 12 38 55 PM |



- Either conditionally apply padding-top or conditionally display the `saved-color` container so it doesn't take up space when empty:

| Current  | Desired  |
|---|---|
| Screen Shot 2020-08-13 at 12 35 55 PM | Screen Shot 2020-08-13 at 12 36 10 PM |

**Comment by jcfranco** [comment]
@macandcheese Thanks for testing! I'll make those changes. 💪

**Comment by bstifle** [comment]
hey yeah i think adam nailed it. no further changes from me, nice work

**Comment by jcfranco** [comment]
@macandcheese Spacing fixed. Thanks again for the feedback!

**Pull request merged**
