### PR TITLE
BREAKING: Various Chip / Combobox updates and enhancements

### LINKED ISSUE #461: [1.0 Release Cleanup] Chip
Breakout issue from https://github.com/Esri/calcite-components/issues/97

### Props
- [x] remove `xs` and `xl` options from `scale`
  - [x] update padding and font-size accordingly

### LINKED ISSUE #462: [1.0 Release Cleanup] Combobox
Breakout issue from https://github.com/Esri/calcite-components/issues/97

### Props
- [x] remove `xs` and `xl` options from `scale`

### LINKED ISSUE #536: Color chips
lets get all the color chips in there!

(or should we call these labels?)

image

### PR DESCRIPTION
**Pull request by macandcheese**
Contains various requested chip updates cc @bstifle @julio8a

BREAKING - removes XS and XL scale from chip
BREAKING - removes XS and XL scale from combobox
Adds "color" prop to chip
Adds "appearance" prop to chip
Updates chip style and dimensions
Adds a set of tests to calcite-chip to test for props and dismissible

Resolves #462, Resolves #461, Resolves #536

### CODE REVIEW

**Comment by paulcpederson** [comment]
This is more notes for @bstifle  I think but a couple design notes:

1. If we know the image is always circular, why not make it seat properly within the rounded chip?Screen Shot 2020-05-15 at 1 17 52 PM
2. The interior spacing between the elements feels a bit too big. It looks good when you have something like ` icon  text  x ` as there is symmetry, but ` icon   text ` feels like it should sit closer together.

| current | closer |
| --- | --- |
| Screen Shot 2020-05-15 at 1 25 28 PM | Screen Shot 2020-05-15 at 1 25 28 PM |

Looks great though, the colors will be super useful, for sure. Nice work @macandcheese

**Comment by macandcheese** [comment]
Cool, yeah I can make those ✨changes ✨ before merging.

**Comment by macandcheese** [comment]
They are actually outline though - there is a set bg color. If we want to add another appearance variant to match buttons that is truly "clear", we can do that additionally.

The blue is coming from the Calcite-color variables so... Should be correct unless it's wrong at the source 🤷‍♂️

**Comment by bstifle** [comment]
@macandcheese 

image maybe just not reflected in this build?

**Comment by macandcheese** [comment]
Ah, yeah I used the wrong variable. I think having a true outline and clear makes sense I can fix this and add that...

**Comment by bstifle** [comment]
I dont think we need to change anything other than the name. Outline with fill doesnt make sense for these... can we keep the fill transparent please? was always the intent

**Comment by macandcheese** [comment]
@bstifle @paulcpederson updated with spacing feedback for slotted image, made "not dismissible with icon" spacing updates, and changed "outline" to "clear" as prop name.

**Comment by bstifle** [comment]
@macandcheese 

image

the x spacing before the icon seems off (too much)

**Comment by macandcheese** [comment]
Yeah that case isn't handled (slotted image, icon, span) - was just testing to see they all rendered in an expected order. Do we want to address that? If so, how?

**Comment by bstifle** [comment]
yeah i was also saying on icon only

**Comment by macandcheese** [comment]
That's just something we'll have to live with, I think... the actual bounding box of the icon is the same distance from the edge as the text. But, all icons fill their bounding boxes in different ways:

Screen Shot 2020-05-18 at 11 24 28 AM
Screen Shot 2020-05-18 at 11 25 31 AM

**Pull request merged**
