### PR TITLE
test(date-picker): updated date-picker demo according to Figma

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2580 

## Summary
- updated calcite-date-picker encompassing the Figma design
- this version includes _small_, _medium_, and _large_ scale, which the previous version failed to include

### CODE REVIEW

**Review by bstifle — APPROVED** [review]
LOOKS GOOD! nice job

**Comment by bstifle** [comment]
@ManahariDahal  looks good, ship it!

**Comment by julio8a** [comment]
@bstifle @caripizza. Do we need all of these? i.e. always open

**Comment by bstifle** [comment]
@julio8a One should be as a dropdown, always open should be when just static on a page

**Comment by julio8a** [comment]
ah, okay. Does it seem most of these need to have a button or something to trigger the calendar?

Are you guys okay with just not having the trigger (button, anchor, etc)? since we really want to see the component. This would mean removing the always open variant. (since the trigger, i.e. button is not part of this component)

**Comment by bstifle** [comment]
@julio8a yeah if its not in dropdown it should just have that "always open" styling (border, no shadow)

**Comment by julio8a** [comment]
So this one needs a few buttons to trigger the floating date picker?

**Comment by ManahariDahal** [comment]
yes, I agree with @julio8a . I will get rid off the _always open_ state.

**Review by julio8a — APPROVED** [review]
Looks good!

**Pull request merged**
