### PR TITLE
refactor(action-bar): match Figma and Tailwind

### PR DESCRIPTION
**Pull request by julio8a**
**Related Issue:** #1500 #2452

## Summary

- These changes affect action and action bar
- Updated spacing between icon and text
- Updated font-weight to medium (it was already using `h`)

Working from the [Figma/Tailwind components refactor project](https://github.com/Esri/calcite-components/projects/14)

Project card: https://github.com/Esri/calcite-components/projects/14#card-60667706

### CODE REVIEW

**Comment by julio8a** [comment]
This is ready for another review.

**Comment by caripizza** [comment]
@julio8a can you merge in a fresh master to this branch? Those Screener changes are confusing me. 

I also see the pr has a "Linked issue" which means it will auto-close once this is merged, which would prevent verifying the issue after installment (might be better to add issue number in description instead).

**Comment by julio8a** [comment]
Okay, this one still has some work. Need to add S and L. Will merge master.

**Comment by julio8a** [comment]
Let's move this one forward since we need to discuss the sizes for this component. @bstifle can you review?

**Comment by julio8a** [comment]
There are some outstanding items I was not able to work on, I will add them to the issue, which will remain open #2452

**Pull request merged**
