### PR TITLE
docs(storybook): fix storybook error.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** N/A

### Error on PRD

```
"TypeError: Cannot read properties of undefined (reading 'map')
    at setTheme (https://esri.github.io/calcite-components/main.e9e11f08.iframe.bundle.js:3961:3525)
    at Module.1088 (https://esri.github.io/calcite-components/main.e9e11f08.iframe.bundle.js:1455:91860)
    at __webpack_require__ (https://esri.github.io/calcite-components/runtime~main.93db795b.iframe.bundle.js:1:1301)
    at webpackContext (https://esri.github.io/calcite-components/main.e9e11f08.iframe.bundle.js:1:4150)
    at https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:3128879
    at Array.forEach (<anonymous>)
    at https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:3128831
    at Array.forEach (<anonymous>)
    at https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:3128797
    at ConfigApi.configure (https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:2711598)"
```

### Fix

- Moves `THEMES` constant from `src/utils/resources.ts` to `.storybook/helpers.ts`.
- This should fix webpack messing up the ability to import themes in storybook.
- Updates helper functions to check for constants before calling `.map` and also filters out any invalid or incomplete objects.

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]
LGTM 👍  Were you able to verify this fix works locally?

**Comment by driskull** [comment]
Seems to be from here:

```"TypeError: Cannot read properties of undefined (reading 'map')
    at setTheme (https://esri.github.io/calcite-components/main.e9e11f08.iframe.bundle.js:3961:3525)
    at Module.1088 (https://esri.github.io/calcite-components/main.e9e11f08.iframe.bundle.js:1455:91860)
    at __webpack_require__ (https://esri.github.io/calcite-components/runtime~main.93db795b.iframe.bundle.js:1:1301)
    at webpackContext (https://esri.github.io/calcite-components/main.e9e11f08.iframe.bundle.js:1:4150)
    at https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:3128879
    at Array.forEach (<anonymous>)
    at https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:3128831
    at Array.forEach (<anonymous>)
    at https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:3128797
    at ConfigApi.configure (https://esri.github.io/calcite-components/vendors~main.0b81f3f8.iframe.bundle.js:6:2711598)"```

**Comment by driskull** [comment]
Seems webpack might be messing up the ability to find the THEMES const from within storybook. I think this should fix it.

**Comment by eriklharper** [comment]
> Seems webpack might be messing up the ability to find the THEMES const from within storybook. I think this should fix it.

Cool, if this does fix it, I'll put up another pr reverting the change I just made to the action story.  Thanks for looking into that @driskull !

**Comment by jcfranco** [comment]
@driskull Can you add more info on the error and fix in the description?

**Comment by driskull** [comment]
Updated

**Comment by jcfranco** [comment]
@driskull Thanks. One more thing, is the error coming from the build or is it a runtime one? If it's the latter, which story?

**Comment by driskull** [comment]
@jcfranco it's a runtime error.  You can see it here: https://esri.github.io/calcite-components/?path=/story/components-action-bar--with-tooltip

**Comment by driskull** [comment]
image

It shows as console warning in browser but it's actually an error that seems to be captured?

**Comment by jcfranco** [comment]
I looked a bit closer and could not find a way to reproduce this locally. I'm guessing it's something that happens when it gets deployed (via [`storybook-deployer`](https://github.com/storybookjs/storybook-deployer)) or when its served on GitHub pages. 

The story linked above seems to be working fine. Are these warnings affecting the stories in some way?

**Comment by driskull** [comment]
> The story linked above seems to be working fine. Are these warnings affecting the stories in some way?

Yes, that is why this came about. The stories with steps aren't being rendered on PRD.

**Comment by driskull** [comment]
@eriklharper you were seeing this on PRD with the action stories right?

**Comment by eriklharper** [comment]
> @eriklharper you were seeing this on PRD with the action stories right?

Yes, it wasn't specific to the action story though, it was just on initial payload because the error occurred during the story loading cycle.

**Comment by jcfranco** [comment]
@eriklharper @driskull Can you check the recently updated storybook page? I'm not seeing the warnings anymore.

**Comment by driskull** [comment]
Yeah looks good now. I'll close this then

**Comment by driskull** [comment]
@eriklharper I think the two action stories are showing now. Can you revert?

**Comment by jcfranco** [comment]
> I think the two action stories are showing now. Can you revert?

I thought any stories using the steps API wouldn't be listed in the storybook. Can you confirm?

**Comment by driskull** [comment]
> I thought any stories using the steps API wouldn't be listed in the storybook. Can you confirm?

Not from my experience. Steps shouldn't affect stories from showing

**Comment by jcfranco** [comment]
Got it. Thanks for confirming.

**Comment by eriklharper** [comment]
What @driskull said.  The steps doesn't affect stories from still showing up as normal in the Storybook UI.  It shows up normally when running storybook dev server and now as part of Matt's fix, now on PRD.  Here's the revert PR, which will require a Screener review since the screenshot's names will change back to "Default".  #3465

**Pull request closed without merging**
