### PR TITLE
fix(combobox): Fix selection logic and prevent events from causing stack error

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2491

## Summary

fix(combobox): Fix selection logic and prevent events from causing stack error. #2491

### CODE REVIEW

**Review by bstifle — APPROVED** [review]

**Comment by bstifle** [comment]
Nice work manahari!

**Review by bstifle — COMMENTED** [review]
whoooooooooops i just approved the wrong PR. sorry @driskull

**Comment by driskull** [comment]
@jcfranco can you review?

**Review by jcfranco — APPROVED** [review]
Can you add a test for this before merging?

**Pull request merged**
