### PR TITLE
test(inline-editable): updated inline-editable demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2630 

## Summary
- updated `calcite-inline-editable` demo page

### CODE REVIEW

**Comment by bstifle** [comment]
Inline editable needs to broken down into S M L columns

Not in accordions.

Rows: No controls, With controls, RTL, Disabled

**Comment by julio8a** [comment]
We shouldn't have the inline editable inputs inside accordions, this hides them from screener. We should get rid of other input types, RTL and disabled should be displayed out with the scales. 

This one might need a design from you @bstifle

**Comment by julio8a** [comment]
This one has RTL and some others don't. For now, I would say let's keep it constant with no RTL until we figure out how we're approaching that. A toggle switch, on the same page, RTL on a different page.

**Comment by ManahariDahal** [comment]
@julio8a removed the RTLs, let me know if this looks good.

**Review by bstifle — APPROVED** [review]
Looking fantastic! 🥇

**Pull request merged**
