### PR TITLE
fix(action-bar): Allow slotting tooltip after initialization

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #3495

## Summary

fix(action-bar): Allow slotting tooltip after initialization.  #3495

- Creates utility to connect and disconnect the slotchange event on a component
- The utility will watch for slotchange events and re-render.

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]
Might be good to add a visual screenshot test to verify this works after setting a delay perhaps?

**Review by jcfranco — APPROVED** [review]
Looks great! Can you add a test before merging?

**Comment by driskull** [comment]
@jcfranco @benelan Can we get an issue/epic to update other components that conditionally use getSlotted() to add this?

**Comment by benelan** [comment]
> @jcfranco @benelan Can we get an issue/epic to update other components that conditionally use getSlotted() to add this?

Sorry, just saw this while verifying. Yeah I'll log an issue.

**Pull request merged**
