### PR TITLE
test(modal): update demo html to match Figma

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2505

## Summary
- updated _calcite-modal_ encompassing the Figma design
- this version includes _small_, _medium_, and _large_ **width & scale**, which the previous version failed to include

Screen Shot 2021-07-12 at 4 38 12 PM

### CODE REVIEW

**Comment by julio8a** [comment]
We might need to update the layout a bit to avoid confusion with the width scales and component scales.

This grouping just looks and feels confusing since the medium and large are far from the column header (width):
image

Maybe something like this, just using negative space for grouping:
image


Thoughts @bstifle?

**Comment by bstifle** [comment]
@ManahariDahal 

modal is a weird one since it uses SML for two properties. Might be more clear if we spell it out like this.

Additionally, i think showing SML scale is more beneficial than SML widths for the second section

image

**Comment by julio8a** [comment]
Nice, I like the specific label with `Width x` 

That makes it much easier to read and understand the props

**Comment by ManahariDahal** [comment]
> @ManahariDahal
> 
> modal is a weird one since it uses SML for two properties. Might be more clear if we spell it out like this.
> 
> Additionally, i think showing SML scale is more beneficial than SML widths for the second section
> 
> image

This design is way better than the one I had. I basically have to rewrite the code for this, haha. I will work on it later today.

**Comment by bstifle** [comment]
@ManahariDahal  looks like the modals being invoked dont match the labels

let's get on a call and iron this out!

**Review by bstifle — APPROVED** [review]
WELL DONE 🍔

**Comment by julio8a** [comment]
LGTM!

**Comment by ManahariDahal** [comment]
> Looks like you have some failing checks. Can you try merging master into your branch?

All checks have passed.

**Comment by julio8a** [comment]
LGTM!

**Pull request merged**
