### PR TITLE
refactor(calcite-dropdown): updated scale l icon size and font size to match figma

### PR DESCRIPTION
**Pull request by bpatterson88**
**Related Issue:** #2041

## Summary

- Updated scale L icon size to S
- Updated scale L font size to 1h

### CODE REVIEW

**Comment by bpatterson88** [comment]
- Updated horizontal spacing based on Figma
- Currently we are using • for the single select bullet (rather than an icon), so getting it to be 4x4px at all sizes would require a new solution.

cc @bstifle

**Comment by jcfranco** [comment]
@bstifle @julio8a Can either of you take a look at this one?

**Comment by bstifle** [comment]
@jcfranco on it!

**Comment by bstifle** [comment]
@bpatterson88 sorry i def missed your comment!!! spacing looks really good.

The only fixes left would be the size of the radio ellipse on Medium and Large. They are both 6px, should be 4px


image

**Comment by bpatterson88** [comment]
@bstifle Updated the M and L radio ellipses to `font--2h`, making them 4px around. Should be good now!

**Review by bstifle — APPROVED** [review]
real nice ben!

**Comment by bstifle** [comment]
@justinhough

**Pull request merged**
