### PR TITLE
feat(list-item): add padding when there is only a label or only a description

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #3362

## Summary
Keeps list-item from being too small when there's only a label or description.

Accomplished by adding padding around `label` or `description` when they are `:only-child`.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
Looks good. Is this covered by a screenshot test?

**Comment by asangma** [comment]
Oh...good question. I'm not sure how to add that.

**Comment by driskull** [comment]
Can you add a list-item with only a child to one of the list item stories?

**Comment by asangma** [comment]
@driskull Does that look right?

**Pull request merged**
