### PR TITLE
docs(storybook): prevent internal attributes from being rendered in HTML preview

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This sets up an 'addon extension' to https://www.npmjs.com/package/@whitespace/storybook-addon-html to intercept our storybook HTML preview content and hide global, internal attributes that may affect component rendering when copying/pasting code.

### CODE REVIEW

**Comment by jcfranco** [comment]
@driskull @paulcpederson @macandcheese Do you think it'd be useful to have this just for hiding the calcite-hydrated attributes from the HTML preview?

**Comment by driskull** [comment]
I think so.

**Review by driskull — APPROVED** [review]
👍 Nice!

**Review by eriklharper — APPROVED** [review]
Excellent! Cheerio looks like a perfect tool for this kind of job.

**Pull request merged**
