### PR TITLE
refactor(pick-list/value-list): change to use calcite-input

### PR DESCRIPTION
**Pull request by justinhough**
**Related Issue:** #1549

## Summary

Issues with users not seeing the filter or missing it entirely based on styling. Direction was to change the input field to use a calcite-input instead of a custom input field to keep consistency across usages.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Code changes LGTM! 

@caripizza Can you review Screener changes after @justinhough merges the latest from master? 🙇🏼‍♂️

**Comment by caripizza** [comment]
@jcfranco It doesn't seem like these changes jive with Travis due to all the fails. I can take another look at why things are failing after I merge in the Screener update.

**Comment by caripizza** [comment]
If we are going to make a change this drastic, we need e2e test coverage. (And any existing tests will need to be fixed since 3 test suites are failing on this pr branch currently.)

**Review by macandcheese — APPROVED** [review]

**Comment by julio8a** [comment]
@justinhough, are you able to work on the tests?

**Pull request merged**
