### PR TITLE
fix(combobox): Visually nest group items properly

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #6384

## Summary

Fix css for nesting group combobox items.

### CODE REVIEW

**Comment by driskull** [comment]
I can haz review? :)

**Review by jcfranco — APPROVED** [review]
Code changes LGTM! 

@ashetland Can you review the visual diffs? 

Good to merge once ☝️ approveth.

**Comment by ashetland** [comment]
It looks like when `items` get slotted into an `item-group`, the var `--calcite-combobox-item-spacing-indent-multiplier` gets bumped by +1: what is 0, 1, 2... when not in a group becomes 1, 2, 3... when in a group. This bumping of the multiplier isn't ideal and complicates the hierarchical relationships when item-groups are used. Is it possible to change this behavior of `item-group`?

**Comment by driskull** [comment]
@ashetland isn't that what the issue is asking for? item-groups should provide nesting indentation?

**Comment by driskull** [comment]
This PR does make it look how it did previously.

**Comment by ashetland** [comment]
Thanks @driskull, you're totally right. This PR fixes the behavior of nesting groups. Should the other behavior fix be logged as its own issue? Sometimes we've been making little fixes like this as we catch them, but maybe that's not the best practice. Happy to log a separate issue if that the preferred approach.

**Comment by driskull** [comment]
> Should the other behavior fix be logged as its own issue

Yes, definitely. Otherwise we get scope creep

**Comment by ashetland** [comment]
Awesome. Approving now. 🚀

**Pull request merged**
