### PR TITLE
fix: (radio group) - apply forced-colors styles

### PR DESCRIPTION
**Pull request by mpriour**
* Adds highlight color to solid selected item
* Adds bold outline to outline selected item
* Modifies icon color on solid selected item for better contrast

**Related Issue:** #4873 

## Summary

Modifies the radio group selections to look like this on High Contrast mode:

Screen Shot of high contrast radio group selection states

Unfortunately, the text *ALWAYS* has its own un-style-able background so it doesn't have the same background as the radio group "button".

### CODE REVIEW

**Comment by mpriour** [comment]
@macandcheese Now that all the tests passed, can you take a look at this to see if you have any further comments or requests on the change for high contrast users.

**Review by driskull — APPROVED** [review]
LGTM!

**Comment by macandcheese** [comment]
Thanks @mpriour - is "outline" strong enough? Not sure if using the highlight color for that outline could help.

I guess it's worth considering if this visual difference is needed for high contrast users, or if there are concerns with "outline", display both as "solid" when in this mode?

**Comment by mpriour** [comment]
@macandcheese I can easily increase the outline thickness. It is 2 pixels now but 4 pixels would be more obvious. I will get some feedback from a real high contrast user at least as well.

**Comment by mpriour** [comment]
@macandcheese Shared changes with a real high contrast user and they thought that the 2px outline was perfect. We experimented with 3px and 4px and both were determined to be too thick.

**Comment by macandcheese** [comment]
> 

Awesome, thanks for checking.

**Pull request merged**
