### PR TITLE
chore: fix build warnings

### PR DESCRIPTION
**Pull request by driskull**
chore: fix build warnings

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]
Thank you sir!

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
Yes!

**Comment by driskull** [comment]
@jcfranco can we get rid of the `calcite-color` console warnings about ignoring invalid color value?

Would wrapping it in a:

```tsx
if (Build.isBrowser) {
}
```
work?

**Comment by jcfranco** [comment]
@driskull I would avoid that since the warning should be displayed regardless where the color picker is used. I could look at stubbing `console.warn` for the any test portion using invalid colors.

**Pull request merged**
