### PR TITLE
fix(modal): Allow modal to focus on calcite components.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1375

## Summary

fix(modal): Allow modal to focus on calcite components.

### CODE REVIEW

**Comment by driskull** [comment]
@jcfranco this is making the test spec files fail. Do you know what I have to do to get this fixed?

**Comment by driskull** [comment]
Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

**Comment by jcfranco** [comment]
@driskull I'd have to look into it. I'd suggest inlining the util in modal for now, unless you want to take on https://github.com/Esri/calcite-components/issues/1292.

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
Thanks, @driskull

**Pull request merged**
