### PR TITLE
feat(action-bar): Automatically overflow actions into a menu depending on available height

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1819

## Summary

Enhancement: improve calcite-action-bar overflow menu handling #1819

### Breaking Changes

- fix(action-menu)!: Replace 'intlOptions' property with 'label'. // BREAKING
- fix(action-group)!: Replace 'intlOptions' property with 'intlMore'. // BREAKING

### Features

- feat(action-bar): Automatically overflow actions into a menu depending on available height.
- feat(action-menu): Add 'tooltip' slot for adding an tooltip for the menu.
- feat(action-bar): Add overflowActionsDisabled property. Allows scrolling again and disables resizeObserver.

### Notes

- Adds "@types/resize-observer-browser": "0.1.5" for resizeObserver typescript typings
- Removes scrolling on action-bar
- Adds label prop for `calcite-action-menu` since `intlOptions` does not make sense since each group contains a different set of actions that need different labeling. This is a breaking change.
- `calcite-action-group` has an `intlMore` prop for changing the text for the menu.
- Update demos

### Questions

- Should we do anything to `calcite-action-pad` to remove it's scrolling support? I'm not sure nested menus make sense for good UX.

Mar-24-2021 12-11-27

### CODE REVIEW

**Review by asangma — CHANGES_REQUESTED** [review]
Sorry if I missed this.
We should have a default string for the overflow menu.
Suggest that string be "More".

image

**Comment by asangma** [comment]
Another thing. 
Right now, it appears that the actions are moved to the overflow from the top action-group first. It seems like we'd want the bottom (last) action-group to start pushing actions to overflow first. And the top (first) action-group should show all actions for as long as possible.

The first shall be last and the last shall be first.

**Comment by driskull** [comment]
> Right now, it appears that the actions are moved to the overflow from the top action-group first.

Not true, it moves from largest group first, then bottom up. The group must also have at least 3 actions to overflow.

**Comment by driskull** [comment]
Removed sorting by group, but that example will still show the same.

**Comment by asangma** [comment]
@driskull Ah...I see.

Do you think there's a reasonable way to make it so that (excluding the bottom-actions slot), the automatic overflow would prioritize as described above?

This is based on the assumption that the highest priority action-group in an app will likely be first in an action-bar, and that action-group will probably often have the most actions in it.

**Review by asangma — APPROVED** [review]
Removing my block on this PR.
`But I think prioritizing action-groups based on their order in the DOM would be a good idea.~

Other than that, this is pretty siiiick!

**Comment by asangma** [comment]
Updated after more testing.
Sorry for the noise.

Looks rad!

**Comment by driskull** [comment]
@jcfranco can you review?

**Comment by jcfranco** [comment]
@driskull Before reviewing, are all of the different fixes and features meant to be squashed? Multiple, independent commits in a single PR don't mesh well with our auto changelog tooling.

**Comment by driskull** [comment]
@jcfranco how should I separate or combine them?

**Comment by jcfranco** [comment]
> how should I separate or combine them?

If you want to keep them separate and isolated, you'll need some git-fu to break off commits/code chunks from the history and submit PRs for each one. Otherwise, you'll have to squash all of the changes and use the best commit type and message to describe all of the changes, making sure to include breaking change info in the commit body (if applicable). 

I know it's more work, but the first option seems the most ideal to me in that it adheres to conventional commits, keeps PRs focused and the changelog will have an entry for each relevant change.

**Comment by driskull** [comment]
Opened:

- #1869
- #1870
- #1871 
- #1872 
- #1873

**Pull request closed without merging**
