### PR TITLE
feat(tree-item): update selection visuals to match Figma

### PR DESCRIPTION
**Pull request by caripizza**
**Related Issue:** #2082 (replacement for pr #2906 due to Screener problems)

## Summary
Updates selected tree-item styles to match Figma, for each tree selection-mode:
- checkmark icon: multi/multi-children
- bullet point icon: single/children
- checkbox input: ancestors

Latest designs from issue:
no lines
lines

### CODE REVIEW

**Comment by caripizza** [comment]
Yep, these are the correct Screener changes showing finally. I'll close out the other pr.

**Comment by caripizza** [comment]
Can someone please re-review this one? It's a replica of my previous pr which Franco/Adam had reviewed previously. (I opened a new pr to troubleshoot Screener false positives on that previous pr branch.)

**Review by jcfranco — APPROVED** [review]
💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥
💥💣💣💣💣💥💥💣💣💥💥💥💣💣💥💥💣💥💥💥💣💥💣💥
💥💣💥💥💣💥💣💥💥💣💥💣💥💥💣💥💣💣💥💣💣💥💣💥
💥💣💣💣💥💥💣💥💥💣💥💣💥💥💣💥💣💥💣💥💣💥💣💥
💥💣💥💥💣💥💣💥💥💣💥💣💥💥💣💥💣💥💥💥💣💥💥💥
💥💣💣💣💣💥💥💣💣💥💥💥💣💣💥💥💣💥💥💥💣💥💣💥
💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥

**Comment by julio8a** [comment]
@macandcheese, please review and approve Screener if all is good.

**Comment by macandcheese** [comment]
Failures on Screener look intended to me - nice cleanup 👍 
Screen Shot 2021-09-10 at 12 47 07 PM

**Pull request merged**
