### PR TITLE
test(dropdown): updated dropdown demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2628 

## Summary
- updated `calcite-dropdown` demo page

### CODE REVIEW

**Comment by bstifle** [comment]
@ManahariDahal 

dropdown demo looks awesome!

noting this again, the divider bars need to use a calcite color variable so it properly switches with the theme:
image

recommend border-2

**Comment by ManahariDahal** [comment]
> @ManahariDahal
> 
> dropdown demo looks awesome!
> 
> noting this again, the divider bars need to use a calcite color variable so it properly switches with the theme:
> image
> 
> recommend border-2

I am using border-2, does it still not work?

**Review by julio8a — APPROVED** [review]
Looks good!

**Comment by ManahariDahal** [comment]
@bstifle needs approval for this too

**Comment by bstifle** [comment]
@ManahariDahal there are a few iterations that need to be in.

- We need to show S M L widths (maybe just use M scale for those)

- We need to show icon-end in all 3 scales
image

- We need to show selection mode:none in all 3 scales

- Show "Can control amount of items displayed"
image

**Comment by bstifle** [comment]
Almost!!

still need to show

1. Icon Start
image


and

2. Icon Start + End
image

**Review by bstifle — APPROVED** [review]
Lookin GREAT ✅

**Pull request merged**
