### PR TITLE
docs(pagination, pick-list-item, slider): Add additional information for label properties

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2517

## Summary

docs(pagination, pick-list-item, slider): Add additional information for label properties. #2517

### CODE REVIEW

**Review by jcfranco — CHANGES_REQUESTED** [review]
Noice! Can you split this up into `docs` and `refactor` PRs?

**Comment by driskull** [comment]
@jcfranco I think ESLint or TSLint is doing that "refactoring".

I can revert it if necessary but I think we can ignore it.

**Comment by jcfranco** [comment]
D-oh, you're right. I thought I had submitted [this linting PR](https://github.com/Esri/calcite-components/pull/3015) already. This is good to merge once it lands.

**Comment by driskull** [comment]
image

**Comment by jcfranco** [comment]
Thanks for reverting and installing! I was about to comment about the linting PR landing. 💥

**Pull request merged**
