### PR TITLE
docs: renames props in docs and demos

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #

## Summary
Replaces "text-" props and replaces with updated prop in docs and demos.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Thanks! 🎉

**Review by driskull — APPROVED** [review]
Awesome!

**Comment by asangma** [comment]
Oops...spaced a few components. Pushes coming.

**Comment by asangma** [comment]
Aight updated.

**Comment by asangma** [comment]
Doing it!

**Pull request merged**
