### PR TITLE
test(input): stabilize e2e tests

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This PR tidies up and stabilizes input E2E tests by:

- using `setContent` after creating the test pages to ensure `await page.waitForChanges()` is called
- removing unnecessary tests and assertions (e.g., asserting prop values match initial values set in the test HTML)
- merging overlapping tests
- use the HTML content to set up test instead of using Puppeteer APIs
- using helpers for common tests
- move tests outside of unrelated groups
- removes irrelevant tests (e.g., inline-editable - this is covered in that component's tests and screenshot tests)
- updates value nudging tests to not rely on the interval delay as it's not guaranteed the browser will call them at that time (see https://codepen.io/jcfranco/pen/VwMQZxW)

This also restores unskipped tests and updates `calcite-input.tsx` to fix some failures and updates associated tests as well. I submitted separate PRs for the fix and a small refactor this to keep this related to test stability and maintenance (https://github.com/Esri/calcite-components/pull/3568, https://github.com/Esri/calcite-components/pull/3569).

### CODE REVIEW

**Comment by jcfranco** [comment]
I think this PR is ready. The last 34 E2E runs only saw the following, **_unrelated_** 🎉, failures:

```
  ● calcite-filter › filter behavior › updates filtered items after filtering

    expect(received).toHaveLength(expected)

    Expected length: 4
    Received length: 6
    Received array:  [{"description": "developer", "metadata": {"favoriteBand": "MetallicA", "haircolor": "red"}, "name": "Harry", "value": "harry"}, {"description": "developer", "metadata": {"favoriteBand": "unknown", "haircolor": "black"}, "name": "Matt", "value": "matt"}, {"description": "developer", "metadata": {"favoriteBand": "The Mars Volta", "haircolor": "black"}, "name": "Franco", "value": "franco"}, {"description": "engineer", "metadata": {"favoriteBand": "unknown", "haircolor": "red"}, "name": "Katy", "value": "katy"}, {"description": "developer", "metadata": {"favoriteBand": "Hippity Hops", "haircolor": "brown"}, "name": "Jon", "value": "jon"}, {"description": "regex", "metadata": {"favoriteBand": "regex()", "haircolor": "rainbow"}, "name": "regex", "value": "regex"}]
```

and I suspect this one was caused by the test runner environment: https://github.com/Esri/calcite-components/runs/4675674585?check_suite_focus=true since there were many component failures with the following error message:

```
App did not load in allowed time. Please ensure the content loads a stencil application.
```

**Review by driskull — APPROVED** [review]
LGTM!

**Pull request merged**
