### PR TITLE
test(link): updated calcite-link demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2632 

## Summary
- updated _calcite-link_ demo update

### CODE REVIEW

**Comment by ManahariDahal** [comment]
@caripizza @julio8a I feel like this design is overkill with all the different states (start, end, start and end icons). What do you guys think?

**Comment by bstifle** [comment]
@ManahariDahal 

Let's try something more like this for the layout:

image

**Review by julio8a — APPROVED** [review]
LGTM

**Comment by ManahariDahal** [comment]
@bstifle need your approval for this

**Review by bstifle — APPROVED** [review]
perfect, nice work 💯

**Comment by bstifle** [comment]
weird stuff going on in that screener. do you need to merge master into this branch first? @julio8a

**Comment by julio8a** [comment]
It looks like it's picking up changes from flow that already went in. I think we can just accept these. 
The ones with the tooltip, we should ignore those as they look like an image when it wasn't fully rendered. I get these every once in a while. 

This branch has conflicts that need to be resolved before we can merge.

**Pull request merged**
