### PR TITLE
test(loader): loader demo updated

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2633 

## Summary
- updated loader demo page

### CODE REVIEW

**Review by bstifle — APPROVED** [review]
lookin good

**Review by julio8a — APPROVED** [review]
Looooooooks good. Same as indeterminate progress, we need to think of the best way auto test these without having Screener call out it's different on every PR.

**Comment by eriklharper** [comment]
Screener has the ability to ignore regions.  In my experience there is no good way to automate visual testing of animations.  We'll just have to rely on good ol' manual human labor for those...

**Comment by julio8a** [comment]
Okey, let's proceed with this one

**Pull request merged**
