### PR TITLE
refactor(date-picker)!: remove deprecated start and end properties

### PR DESCRIPTION
**Pull request by eriklharper**
BREAKING CHANGE: Removed the `start` and `end` properties, set `value` as an array with the start as the first value and the end as the second value instead.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Review by benelan — COMMENTED** [review]
The properties are used in the demos, can you remove them there as well please

**Comment by benelan** [comment]
And the usage snippets

**Comment by driskull** [comment]
Don't forget to sniff out all the places these things are used. demos, usage, stories, etc.

I will find them later if not now 😈

**Pull request merged**
