### PR TITLE
build: Add rollup and tslib to allow for changing branches while server is running

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #

## Summary

This fixes a rollup error that occurs when switching branches and the demo server is running.

build: Add rollup and tslib to allow for changing branches while server is running

### CODE REVIEW

**Comment by jcfranco** [comment]
Interesting. Could you add more info about the error, what caused it and how this fixes it? Looking at the changes, I thought it was related to the ES5 output, but that's only enabled for production. From what I understand, the Stencil build takes care of this and doesn't downlevel emit, but I could be wrong.

**Comment by driskull** [comment]
This is reproducible by:

- npm start on master
- wait for server to be setup
- switch to a branch that has a lot of file changes
- notice that a rollup error occurs

image

```
[28:47.2]  copy finished (107 files) in 2.26 s
[29:02.4]  generate lazy finished in 17.41 s
[29:13.9]  generate hydrate app finished in 28.93 s

[ ERROR ]  Rollup: Parse Error: ./node_modules/@stencil/core/compiler/stencil.js:23708:26
           Unexpected token

  L23707:  TextMetrics: C,
  L23708:  TextTrack: C, 
  L23709:  TextTrackCue: C,

[29:13.9]  rebuild failed, watching for changes... in 36.95 s
```

https://github.com/ionic-team/stencil/issues/1305
https://github.com/rollup/plugins/issues/287

**Comment by jcfranco** [comment]
Thanks for the additional info. 

Unfortunately, I'm still seeing the build error with this and I'm now getting an out-of-memory error (possibly to an extra TS build?): 

```cli
[ ERROR ]  Rollup: Parse Error: ./node_modules/@stencil/core/compiler/stencil.js:23708:26
           Unexpected token

  L23707:  TextMetrics: C,
  L23708:  TextTrack: C,
  L23709:  TextTrackCue: C,

[03:57.8]  rebuild failed, watching for changes... in 54.83 s


<--- Last few GCs --->

[83882:0x104e00000]   936690 ms: Mark-sweep (reduce) 4083.0 (4105.4) -> 4082.7 (4105.9) MB, 4915.5 / 0.0 ms  (average mu = 0.106, current mu = 0.001) allocation failure scavenge might not succeed
[83882:0x104e00000]   940900 ms: Mark-sweep (reduce) 4083.8 (4102.9) -> 4083.3 (4104.6) MB, 4205.1 / 0.1 ms  (average mu = 0.058, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```

It'd be nice to get some additional info on what the issue is and how the changes in this PR address it. I'm also not sure where the `tslib` came from since it's not referenced in the linked issues.

**Comment by driskull** [comment]
Ok i'll close this.

**Comment by jcfranco** [comment]
FWIW, the out-of-memory error seems to be unrelated to these changes. I got the error during a rebase.

**Pull request closed without merging**
