### PR TITLE
test(scrim): updated demo design using flexbox with two rows

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2605 

## Summary
- updated demo page
- used flexbox with two rows

### CODE REVIEW

**Review by julio8a — APPROVED** [review]

**Comment by bstifle** [comment]
@ManahariDahal 
image


im seeing 2 of everything.... i prefer the presentation on top

**Review by julio8a — APPROVED** [review]
Nice, we might just need to one without the loading indicator, as Screener will always see this as a change when it takes a screenshot, but leave the loading there, for now, we can easily remove it later if needed.

**Comment by ManahariDahal** [comment]
> Nice, we might just need to one without the loading indicator, as Screener will always see this as a change when it takes a screenshot, but leave the loading there, for now, we can easily remove it later if needed.

The screener test passed, but Travis CI didn't. Should I trigger Travis CI and we can leave the loading indicator if the screener passes again. What do you think?

**Comment by julio8a** [comment]
Yes

**Review by bstifle — APPROVED** [review]
skrimtiful!

**Comment by ManahariDahal** [comment]
Ready to merge!

**Pull request merged**
