### PR TITLE
RadioGroup - add width prop

### PR DESCRIPTION
**Pull request by asangma**
re #615

* Added `width` prop to RadioGroup
* Added related styles to RadioGroup
* Added related styles for RadioGroupItem
* e2e
* readme

### CODE REVIEW

**Comment by paulcpederson** [comment]
💯 top marks, best in show

**Comment by asangma** [comment]
Thanks @paulcpederson @macandcheese.
I'll add the Storybook. You'll have to instruct me on the changelog.

**Comment by asangma** [comment]
Updated with Storybook and small CSS tweak regarding the weird vertical + full width.

**Comment by macandcheese** [comment]
Re: changelog, I'd probably just add an "Added" heading under "Unreleased" and something like:

- `calcite-radio-group` now has a `width` prop that accepts `auto` (default) or `full` values

Thanks for adding this!

**Comment by asangma** [comment]
Thanks @macandcheese. Will do.

**Comment by asangma** [comment]
Thanks y'all. CHANGELOG updated. Murgling.

**Pull request merged**
