### PR TITLE
refactor(action-bar, action-pad)!: Removing y scrolling from action-bar and action-pad.  #1656

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1656

## Summary

refactor(action-bar, action-pad)!: Removing y scrolling from action-bar and action-pad.  #1656

### CODE REVIEW

**Comment by asangma** [comment]
@driskull Are we able to let the action-bar content scroll while keeping the bottom group sticky?

**Comment by driskull** [comment]
@asangma I don't think we want the action-bar to scroll at all.

**Comment by asangma** [comment]
The original design was to have the bottom action stay sticky and then let the main portion scroll.
We had that in a while ago. It would help solve the issues where the expand/collapse toggle gets hidden when a display is short.

**Comment by driskull** [comment]
@asangma I don't think it's ideal for a toolbar to scroll. We introduced the `...` menu option, we should probably have them use that instead of scrolling.

**Comment by asangma** [comment]
@driskull It's not ideal, but it's practical.

I agree that the overflow `...` option is nice, but seems like we'd want something basic to built in that would avoid functionality not being accessible due to display size.

**Comment by driskull** [comment]
@asangma I think the scrollbar was a quick-fix that creates other issues. We should really promote not having a toolbar scroll and for the user to just slot actions if they run out of room.

We already have something built in, they just slot `menu-actions` in `calcite-action-group`.

The scrollbar has issues with opening inside and covering icons and such. It's really not ideal at all.

**Comment by asangma** [comment]
Sounds good.

**Comment by asangma** [comment]
Actually...could we review those scrollbar issues together?

**Comment by driskull** [comment]
keep open :)

**Comment by ethanbdev** [comment]
Hey @driskull , If this is a small fix could we still pick it up for beta.52?

**Comment by driskull** [comment]
will handle in #1828

**Pull request closed without merging**
