### PR TITLE
test(pagination): updated pagination demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2634 

## Summary
- updated pagination demo page

### CODE REVIEW

**Review by julio8a — DISMISSED** [review]
Not sure why we need so many on here. I would just keep the first two rows.

image

**Comment by ManahariDahal** [comment]
> Not sure why we need so many on here. I would just keep the first two rows.
> 
> image

just wanted to show some variations 😄 , but I will remove them as requested

**Comment by julio8a** [comment]
Thank you! :)

**Comment by bstifle** [comment]
@ManahariDahal 

The differences between the rows aren't very helpful for review:
image


Can we do something more like this?:
1st row: 3 pages
2nd row: 12 pages
3rd row: 1500 pages
(no 4th row)

**Review by ManahariDahal — COMMENTED** [review]
updated to three rows

**Comment by ManahariDahal** [comment]
cc @bstifle @julio8a ready to be reviewed.

**Review by julio8a — APPROVED** [review]
Looks good!

**Comment by bstifle** [comment]
matthew mcconaughey alright


ship it! merge it! nice one

**Pull request merged**
