### PR TITLE
fix: fix build on windows (#2697)

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** #2697

## Summary

Worked on a windows virtual machine to troubleshoot this issue. The original windows issue (tailwind/sass error) seems to be fine now, not sure if an upgrade fixed that. This pr updates a couple files so the build on windows goes all the way through. There were a few (valid) linter errors being thrown, but after this it seems to work great!

### CODE REVIEW

**Review by driskull — APPROVED** [review]

**Comment by paulcpederson** [comment]
Nice, all the tests pass 😄

**Comment by jcfranco** [comment]
Awesome, thanks for fixing this! 

@benelan Can we remove this from the changelog since it isn't a user-facing fix?

**Comment by benelan** [comment]
Yeah, I made a note of it for when I release on Monday

**Comment by jcfranco** [comment]
Sweet, thanks!

**Pull request merged**
