### PR TITLE
fix(tooltip, popover): Support transparent backgrounds

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #6798

## Summary

- Uses css `clip-path` instead of `transform: rotate` to create the caret arrow tail.
- Removes CSS where we are setting the BG on two separate elements.
- Screener tests

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
🎉

**Comment by driskull** [comment]
@jcfranco @ashetland Let me know if you'd like to proceed with this or not.

**Comment by ashetland** [comment]
Losing the border on the arrow is a deal breaker for me on this one. Without the border, the arrow practically disappears and thus reads like a bug. I think supporting transparency, even if minimal, is valid though. What would it mean to support it? Are we talking breaking changes / major rework?

**Comment by driskull** [comment]
@jcfranco you'll have to make the call on what is more important here.

If we have an arrow behind an arrow that will defeat the purpose of transparency as well due to compounding background colors.

**Comment by driskull** [comment]
Going to close this as it's not possible to use just clip-path and have a border with it. I even tried putting a rotated box div inside and trying to clip it but it still didn't render correctly.

Going forward, we may want to introduce an internal component (possibly functional component) to handle rendering a triangle SVG and styling it with a stroke/fill.

See: https://github.com/floating-ui/floating-ui/pull/2195

CSS just isn't good at doing this even in 2023.

**Pull request closed without merging**
