### PR TITLE
chore(tip, tip-group, tip-manager): ui alignment

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #902

## Summary
UI alignment with Notice.

### CODE REVIEW

**Comment by macandcheese** [comment]
Can you post screenshots here? Couple q's...

Wouldn't noticed have a different use case / need for border and shadow whereas those contained in a tip manager wouldn't? Can tips be used on there own?

 If so, should they be consolidated with notice or are the use cases and UI different enough to justify having both?

**Comment by asangma** [comment]
@macandcheese At a high level, the tip may really only make sense in the TipManager if we can revisit the neutral and flat Notice style (i.e. no box-shadow and either no border or a gray one).

Does Notice have an image slot?

The Tip inside the TipManager looks better sans border.

Tip
image

Tip close button :hover
image

TipManager with Tips (no border)
image


Note: the font weights here seem weird and is something I wanna figure out with someone at some point.

**Comment by asangma** [comment]
As a note, @macandcheese, I am totes down to getting rid of the Tip because outside of the TipManager, Notices can do a lot of the work, and even inside the TipManager, Cards could do the work.

That being said, Tips are currently used, so we'd wanna deprecated Tip and let it survive for a couple releases.

**Comment by asangma** [comment]
Put another way @macandcheese, I just wanna at least align these styles and handle component duplication and deprecation as part of a different discussion and PR.

None of these style alignment PRs are meant to intend long term retention of anything.

**Comment by macandcheese** [comment]
Notice doesn't have an image slot. I see what you mean, tip really fits in tip manager, but Notice performs all of that for inline / in content notices. It doesn't have a border-radius, or a border, just a box-shadow and a left-border. I think we could add a grey border as a state but would want to probably defer to using Notice in situations like that. I'll loop in cc @bstifle to help sort that out.

**Comment by bstifle** [comment]
Wouldnt that be something other than a Notice at that point? like a horizontal dismissible card?

**Comment by macandcheese** [comment]
If we decide that use case for tips outside of tip-manager can be solved by notice, maybe naming tip-manager to tips would help enforce that use case as just items that are placed in a carousel of tips vs. a container for tips that can be used anywhere in a UI.

**Comment by bstifle** [comment]
ok ok ok ok ok ok ok. @asangma 

Im fine with a gray left border for something less status-esque.

Are you ok with not having an image slot in notice? 

Can we work together on the tip-manager? would be nice to tighten up the layout a tad if the requirements allow for it

**Comment by asangma** [comment]
@bstifle Definitely lets talk about the image slot, tip-manager, as well as the other places where we can consolidate. There are some broader philosophical discussions that will play into those discussions. Let's do it as a separate discussion. 

In the meantime, I would like to get the newly ported components visually aligned to address #902.

**Comment by asangma** [comment]
I'm gonna go ahead and mergle this and move onto other newly ported components, cool?

**Comment by asangma** [comment]
After nixing the border radius.

**Comment by asangma** [comment]
@bstifle @macandcheese Starting [a wiki](https://github.com/Esri/calcite-components/wiki/Component-Overlaps) that we can add to once we have discussions.

**Comment by macandcheese** [comment]
Could we keep that info somewhere on Teams / SharePoint so it's not public until we have a better story around this?

**Pull request merged**
