### PR TITLE
feat: unify all assets in distributable output

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This introduces a new pattern (see contributing README changes) for component assets to ensure that the distributable output has a unified assets folder. This will make it easier for consumers to copy all assets if they use the `dist-custom-elements-bundle` output (see https://stenciljs.com/docs/custom-elements#example-bundler-configs).

### Question

Should add a suggestion to nest assets under directories if applicable? For example, instead of

```
calcite-icon/
  assets/
    calcite-icon/
      icon-a.json
      ...
```

we would recommend

```
calcite-icon/
  assets/
    calcite-icon/
      icons/       ⬅  gives context to content
        icon-a.json
        ...
```

It adds an extra folder, but it makes the asset content clearer.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
awesome 👍 🎉

**Review by macandcheese — APPROVED** [review]
🤤

**Review by eriklharper — APPROVED** [review]
👍  cool!

**Comment by paulcpederson** [comment]
Once we do this we should make sure the examples code still works. I think we use a wildcard for all json, but will be good to validate that.

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
@jcfranco looks like some tests need to be updated to reference the date json files in their new location

**Comment by jcfranco** [comment]
Fixed tests. ✨🔨 ✨

> Once we do this we should make sure the examples code still works. I think we use a wildcard for all json, but will be good to validate that.

@paulcpederson which examples are you referring to?

**Comment by paulcpederson** [comment]
Was referring to https://github.com/arcgis/calcite-components-examples  Most of those have code that copies over assets, and I think it will still work, but once this is in a release, will be good to verify.

**Comment by paulcpederson** [comment]
I think you pr is actually going to fix several of these as they are only looking for `/assets`... 😆

**Comment by jcfranco** [comment]
Awesome, thanks for the info. I can double check everything works fine once `@next` gets updated.

**Pull request merged**
