### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by jcfranco**
BETA21

### CODE REVIEW

**Comment by macandcheese** [comment]
Looks good! Only note is I think we still have the filled prop on icon : https://github.com/Esri/calcite-components/blob/b8d12b0855367a47630bfe93319a4e08e8cc31df/src/components/calcite-icon/calcite-icon.tsx#L45

**Comment by jcfranco** [comment]
> - `calcite-icon` - drop `filled` prop as it's no longer valid with the latest calcite UI icons

Is it the phrasing then? `filled` doesn't do anything anymore, right?

**Comment by jcfranco** [comment]
`calcite-icon` now uses JSON path data. Only 15 icons (counting all 3 sizes per icon as 1) have a filled version. For the rest (455), it's broken. For this reason, I'd rather doc it as the prop being dropped.

I'll proceed with the current changelog changes and can submit a follow-up PR if need be.

**Comment by macandcheese** [comment]
Sounds good, just meant we can actually remove the Prop from component when the open issue in Calcite-ui-icon to change their naming structure is added :)

**Comment by jcfranco** [comment]
Got it, thanks. 👌

**Pull request merged**
