### PR TITLE
build(deps): bump versions

### PR DESCRIPTION
**Pull request by jcfranco**
The latest Stencil release has a fix for IE11. Components work now, but I did notice still some styling issues, which I'm not sure if it's a regression or just the state of our IE11 support. @paulcpederson @macandcheese Could one of you help me out with this?

### CODE REVIEW

**Comment by macandcheese** [comment]
What were the styling issues? There are a couple PR I just opened to fix some existing ones from earlier (mostly just needing to duplicate CSS vars for components that have nested children)

**Comment by jcfranco** [comment]
That could be it. I noticed it in the dropdown items.

**Comment by macandcheese** [comment]
The two open PR should help, I think any other outstanding IE11 things have open issues from the initial comb through, this can probably get merged since anything off in IE11 was likely an existing issue 🤷‍♂️

**Comment by jcfranco** [comment]
OK, I'll merge this then.

**Pull request merged**
