### PR TITLE
feat!: Use HTML classes instead of custom 'theme' attributes for theming components

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2262 #2189

## Summary

feat!: Use HTML classes instead of custom 'theme' attributes for theming components #2262 #2189

BREAKING CHANGE: Using a 'theme' attribute is no longer supported to theme a component. Instead, a HTML class attribute of 'calcite-theme-light', 'calcite-theme-dark', or 'calcite-theme-auto' should be set on a component or one of its parent elements. Example: `<calcite-button theme="light" />` now becomes `<calcite-button class="calcite-theme-light" />`. The `calcite-theme-auto` class will defer to the browser's CSS 'prefers-color-scheme' media query to decide whether the light or dark theme will be used.

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]

**Comment by jcfranco** [comment]
@driskull Can you hold off on merging this until we release today?

**Comment by jcfranco** [comment]
@driskull Actually, you can merge when ready. 

Also, the last release had a, premature, note on [breaking changes related to this](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#-breaking-changes). Should we edit the changelog and remove that note in favor of this one?

**Comment by driskull** [comment]
> BTW, the last release had a, premature, note on breaking changes related to this. Should we edit the changelog and remove that note in favor of this one?

Maybe we should leave both? The last one removed the props but the css selectors were still there working.

**Comment by jcfranco** [comment]
Sounds good. Leaving for now. 👍🏼

**Pull request merged**
