### PR TITLE
Updates css to use host-context, fix some RTL styling issues

### PR DESCRIPTION
**Pull request by macandcheese**
Fixes instances of RTL declarations that had chained attributes that weren't updated in the IE fix. I think this is most of them. Also cleans up a couple of RTL styling bugs that were probably there before :)

- Updates some remaining css to use host-context, should fix most issues
- Removes theme example from alert dev demo, cleans up some dev demos
- Swaps icon orientation in pagination RTL
- Fixes spacing in RTL tabs

### CODE REVIEW

**Comment by paulcpederson** [comment]
beautiful 💯

**Comment by jcfranco** [comment]
Does Stencil transform `host-context` into something else? Browser support isn't there yet: https://caniuse.com/#search=host-context

**Comment by jcfranco** [comment]
FWIW, `Ionic` components do use it: https://github.com/ionic-team/ionic/search?q=host-context&type=

**Comment by jcfranco** [comment]
Stencil be like... 

giphy

**Comment by paulcpederson** [comment]
@jcfranco so it doesn't work on a normal dev build in firefox, but if you do a production build it does.

Safari on the other hand...

**Comment by macandcheese** [comment]
Yeah, :host-context doesn't seem to work in Safari, or FF (even with production build, it seems). However, it works in IE and the correct values are in the generated classes (`sc-calcite-dropdown-item-134-h`) so it must be getting polyfilled in some manner...

**Comment by macandcheese** [comment]
So, this was just to clean up a few instances of host-context that weren't changed in the bigger PR earlier. Should we merge this and just hold on releasing a new version until Stencil gets back to us with a potential fix for host context (two open issues w Ionic currently)? Or roll back the earlier one and close this, until we know more?

**Comment by paulcpederson** [comment]
@macandcheese I guess it would be better to close this and revert the work that doesn't work in safari

**Comment by macandcheese** [comment]
Yes, Stencil just replied to our open issue and said it is not supported. Closing.

**Pull request closed without merging**
