### PR TITLE
feat(button): Display text with loading and add disabled styling. #2420

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2420

## Summary

feat(button): Display text with loading and add disabled styling. #2420

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
💥

**Comment by driskull** [comment]
If we need to adjust the margin or animation i'll let a designer take that part.

**Review by macandcheese — APPROVED** [review]
I think this looks good - couple things, both shown in screen cap of demo page:

- Maybe try a width transition for when the loader is appended to the button cc @bstifle 
- A "just icon" button should expand with adequate x padding, it's a little squished right now

https://user-images.githubusercontent.com/4733155/124673191-42e46d00-de6d-11eb-873c-d63d814b45ac.mp4

**Comment by driskull** [comment]
@macandcheese can we merge and submit a styling followup issue for @bstifle?

**Pull request merged**
