### PR TITLE
fix(calcite-slider): slider handle position changes on mousedown instead of click/mouseup

### PR DESCRIPTION
**Pull request by eriklharper**
**Related Issue:** #1497

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Nice! 

I know dragging in puppeteer is a drag (badumtss :drum:), but is there a way to add a test for this?

**Review by driskull — APPROVED** [review]
Nice! Slider working well. This is a sweet UX improvement.

**Comment by eriklharper** [comment]
> Nice!
> 
> I know dragging in puppeteer is a drag (badumtss 🥁), but is there a way to add a test for this?

Sure would be, yes.  I'll look into that next.  pptr.dev does have some docs on mousedown events, that could perhaps work.

**Comment by eriklharper** [comment]
Added a bunch of tests for single and range values, both single-clicking the track and clicking and dragging the track for both.

**Pull request merged**
