### PR TITLE
feat(tile-select-group): add layout prop for vertical tile select

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** #1020

## Summary

Saw issue #1020 about documenting this behavior, but I don't think it was actually possible. I've also added a test suite for the group component as it now has a prop.

### CODE REVIEW

**Comment by macandcheese** [comment]
⬆️
⬇️

**Review by macandcheese — APPROVED** [review]

**Comment by bstifle** [comment]
@paulcpederson looks like the styling for active borders sticks after it's been selected then unselected

image

**Comment by bstifle** [comment]
image
ah its doing that everywhere. somethin broke'd!

**Comment by bstifle** [comment]
gah. looks like these bugs were already in master.

**Review by eriklharper — APPROVED** [review]
Looks like a good addition!  I'll take a peek at the highlighting issue.  We really could use some visual snapshotting to catch these kinds of things.  Hopefully screener will get shadow support soon.

**Pull request merged**
