### PR TITLE
Fix for CSS vars in IE11

### PR DESCRIPTION
**Pull request by macandcheese**
This PR fixes the CSS variable issues that were causing IE11 issues:

- Removes global `calcite.css` requirement (🎈)
- Updates structure of injected CSS
- Various docs and component updates

The extra included css variables in the required `calcite.css` file, combined with the existing css variables we set on the injected styles, were causing those DOMException errors we'd see in IE11 (which would end up as some "host already declared" errors of you could cause a re render).

Consumers can override css variables for each individual theme with the following syntax (although this remains undocumented, and probably should for awhile until we have a better story around it). If `*[theme="dark"]` values are not explicitly overridden, they will inherit the overridden `*` values.

Assuming a wrapping div around the app (although it works on `:root *` as well...)
```
.my-custom-theme-wrapper * {
--calcite-ui-red: salmon;
}

.my-custom-theme-wrapper *[theme="dark"] {
--calcite-ui-red: lightcoral;
}
```

There shouldn't be any breaking changes to consumers, aside from not needing to import a `calcite.css` file anymore

Thank you @paulcpederson for working through this with me🥇.

There are still a lot of IE11 bugs, both functionally and in CSS, but now we can actually see what they are and open issues to get them fixed 😆 !

- There are a couple styles that were removed from the global includes we'll need to update, as well as probably programmatically adding the overflow classes from `calcite-modal` from within the component itself.

- Avenir Next is now declared as the `font-family` on each of the demo pages and in Storybook explicitly, so consumers will have to do the same thing....

- There were also a couple of stray css items in the included CSS that I removed that should be verified.

- It seems like some css vars are not correctly inheriting the dark theme (ie it works in Alerts, Notice, but not in Accordion, Dropdown) for certain variables like text. Need to get that figured out.

Because of all the above I will open this as a draft PR until we get some more eyes on it and some of those bugs straightened out. Once this is merged in we can begin to open issues for each of the remaining IE 11 bugs.

### CODE REVIEW

**Comment by macandcheese** [comment]
Regarding "It seems like some css vars are not correctly inheriting the dark theme (ie it works in Alerts, Notice, but not in Accordion, Dropdown) for certain variables like text. Need to get that figured out."

- It works OOTB on components that do not have children (Alerts, Notice, etc.). Components that have child components (Accordion, Dropdown) need to have theme explicitly set on their `:host` otherwise the injected CSS vars will think the component is not in "dark mode". A small annoyance, but, all CSS works, just need to ensure each component has a theme set via `getElementTheme()`

**Comment by driskull** [comment]
Its kind of a bummer we would remove the global CSS requirement because its much better when the CSS vars are only defined once via root than multiple times via each host.

Can't we create an issue for Stencil to fix instead?

**Comment by paulcpederson** [comment]
@driskull that's how I thought it worked too, but currently on `master` it's not. We are using the same file to inject styles into all the components and in the global css, so all the vars are in fact already declared twice:

Screen Shot 2020-03-06 at 10 24 44 AM

I think I figured this out, though, have an approach that seems to work well to only declare these once. will commit

**Comment by paulcpederson** [comment]
@jcfranco OK, I think I got this figured out, opened a new pr: https://github.com/Esri/calcite-components/pull/363

**Pull request closed without merging**
