### PR TITLE
fix(date-picker): update the calendar instantly as the year changes

### PR DESCRIPTION
**Pull request by eriklharper**
**Related Issue:** #3979 

## Summary

This PR changes the date picker behavior to automatically refresh the calendar as a new year is being entered, either via typing it manually or using the up/down keys to increment or decrement.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Awesome. Can you update the E2E test before merging this?

**Comment by eriklharper** [comment]
> Awesome. Can you update the E2E test before merging this?

I was actually thinking this would be a good candidate for a Screener snapshot test because we can visually see the month changing when the year changes.  Unless you had a specific test in mind that I would need to update or were just hoping to add a new test that verifies it works on input instead of change.

**Comment by jcfranco** [comment]
This is more of a behavioral fix vs visual, so I think E2E would be more appropriate. Off the top of my head, I think the simplest test would be to check that the date value updates as the input changes but before the value is committed (i.e., enter or blur).

**Comment by eriklharper** [comment]
Oh, sorry, I should have clarified the fix here.  The fix is only to refresh the month view when the year changes, not update the stored date value.  That's why I think it will be better as a visual test.  I can write a step story that changes the year to a leap year which will show an extra day in February in the snapshot.  That would be a good one to visually confirm that the change is happening on input rather than pressing enter first or blurring the year.

**Comment by eriklharper** [comment]
I opted to make this an E2E test instead of a screener snapshot due to the lack of an ability to type in the input.

**Review by jcfranco — APPROVED** [review]
Awesome! This is good to merge after simplifying the E2E test.

**Pull request merged**
