### PR TITLE
refactor: clear timeouts on components

### PR DESCRIPTION
**Pull request by driskull**
refactor(action-menu, alert, dropdown, inline-editable, input-date-picker, modal): clear timeouts

### CODE REVIEW

**Comment by driskull** [comment]
Should we have a convention for when using timeouts to clear them?

The animation event issue may render this obsolete. https://github.com/Esri/calcite-components/issues/1602

**Review by jcfranco — APPROVED** [review]
Nice! 👍

**Comment by jcfranco** [comment]
> Should we have a convention for when using timeouts to clear them?

Yeah. Maybe a note on cleaning up resources as a best practice to cover more scenarios.

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
LGTM, feel free to merge

**Review by macandcheese — APPROVED** [review]

**Pull request merged**
