### PR TITLE
fix(tab): remove the scroll that pops up regardless of any width size (#3279)

### PR DESCRIPTION
**Pull request by y0n4**
**Related Issue:** #3279

## Summary
It seems like from what @asangma shared, the tab titles were affecting the width scroll. Now with set width or no width, the horizontal scroll will not show

Before
Screen Shot 2021-12-15 at 1 46 11 PM

After
Screen Shot 2021-12-15 at 1 45 25 PM

I also added a one-line fix from issue #3541

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Code LGTM! I'll let @caripizza chime in on the visual changes. 🎨  👀

**Comment by caripizza** [comment]
I think removing the negative margin messes up more than it's fixing here, since those e2e tests are failing along with the stories. (Tab-nav's active indicator styles seem to rely on this margin for placement currently.)

@asangma if you add `width: 100%; overflow-x: hidden;` on the parent calcite-tabs, it seems to fix the issue/prevent the horizontal scrollbars in your CodePen. Can we do something like that instead here?

```html
<calcite-tabs layout="center" position="above"  style="width: 100%; overflow-x: hidden;">
...
```

**Comment by asangma** [comment]
@y0n4 Hmmm...I'm seeing the same scrolling issue in compact spaces. I think it's worth it to fix this in the component. IMO, negative margins are probably not a thing we should do.

I'll pull the branch and have a look.

**Comment by jcfranco** [comment]
Any updates on this one @asangma?

**Pull request merged**
