### PR TITLE
feat(chip): allow passing avatar as chip image

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** n/a

## Summary

This allows passing an avatar to a chip as per discussion yesterday. 

```html
<calcite-chip>
    <calcite-avatar slot="chip-image" user-id="a81470986eaeee1833b74b7d8abcd5b2" username="cw" />
    Carol Whitten
</calcite-chip>
```

@bstifle on the gray of the chip, the backgrounds were really hard to distinguish, so I lowered the lightness a bit. Had to tweak the initials font sizes a little as well so they wouldn't get cramped in this slightly smaller container. Take a 👀  and we can tweak as needed.

### CODE REVIEW

**Comment by macandcheese** [comment]
* insert Avatar movie gif here * 

Nice! Could you add a quick example of this to the `calcite-chip` storybook page?

**Comment by paulcpederson** [comment]
@macandcheese good call, updated

**Comment by paulcpederson** [comment]
I'm going to merge this in so it makes the release going out today, we can always follow up with design tweeks.

**Comment by bstifle** [comment]
Looks good for now go ahead and mer—

👌🏻

**Pull request merged**
