### PR TITLE
fix(list, list-item): UI tweaks to better match other lists

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #2541 

## Summary
A few small style tweaks to match existing lists (value and pick).
Also includes some demo tweaks for the halps.

cc @AdelheidF

### CODE REVIEW

**Comment by asangma** [comment]
@bstifle Feel free to have this a look gander see. It's a little tweaked from what we reviewed, but as @AdelheidF points out, it strays from our existing lists.

We can also revisit our earlier updates when we refactor.

**Comment by bstifle** [comment]
@asangma what were the tweaks, at a high level?

**Comment by asangma** [comment]
* y-padding is now 0.5rem (was 0.75rem)
* Added 1px margin and box-shadow border between items (except last-child)
* made list bg-color transparent

**Comment by bstifle** [comment]
dig it

**Review by bstifle — CHANGES_REQUESTED** [review]
image

Looks good @asangma but youre dishonoring jake the dog by omitting his pic

**Comment by asangma** [comment]
That's funny @bstifle. But I'd like to get this in for the sprint. :)

**Comment by asangma** [comment]
Updated PR with previous padding values.
y padding in pick-list-item was [updated](https://github.com/Esri/calcite-components/commit/fd0c1926a221c5039ea671efab9428d56e4e2a84#diff-09662305e87ed34c93da0a2d36016063cdde0eba67926b49a3b43799e72585f4R37) in an unrelated PR.

cc @bstifle

**Review by bstifle — APPROVED** [review]

**Comment by asangma** [comment]
@driskull Mind giving this a quick once over before I murgle?

**Comment by driskull** [comment]
Code looks good. I'll leave the padding up to you guys :)

**Comment by asangma** [comment]
Thanks @driskull!

**Pull request merged**
