### PR TITLE
fix(dropdown): Correct placement when opening

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #5102

## Summary

fix(dropdown): Correct placement when opening. (#5102)

The dropdown group needs to remain visible so floating UI can calculate its height. Instead, we set the width/height on its container to be 0 when not opened. This prevents the dropdown group from taking up space when not opened.

cc @benelan

### CODE REVIEW

**Comment by driskull** [comment]
@benelan can you test this with that sample? I tested it and it seemed to fix the problem.

**Comment by benelan** [comment]
It's definetly a lot better. I had to resize and refresh for a good minute before I was able to reproduce the issue
image

And then after refreshing again (and not resizing) the issue goes away. Super weird

**Comment by driskull** [comment]
@benelan In that case, can you call `reposition()` when it is messed up?

**Comment by benelan** [comment]
Yeah that fixes it 
image

**Comment by driskull** [comment]
I think we should proceed.

**Comment by benelan** [comment]
> I think we should proceed.

Yeah I agree, it definitely helped a lot. It repros way less often now. It's not ideal, but positioning it w/ CSS fixes the issue since it only repros when using the JSAPI's View UI for placement.

```css
calcite-dropdown {
  position: fixed;
  z-index: 1;
  bottom: 2rem;
  right: 1rem;
} 
```

As you suggested, it seems like this fixes it too.
```js
document.addEventListener("calciteDropdownBeforeOpen", ({ target }) =>
  target.reposition()
);
```

**Review by jcfranco — APPROVED** [review]
💥

**Comment by jcfranco** [comment]
@driskull WDYT about introducing a prop for floating-UI-owning components to opt into the [autoUpdate](https://floating-ui.com/docs/autoUpdate) behavior? It could help eliminate boilerplate code across apps for these types of scenarios.

**Comment by driskull** [comment]
@jcfranco we do use that for every floatingUI component already. Here: https://github.com/Esri/calcite-components/blob/master/src/utils/floating-ui.ts#L381

**Comment by driskull** [comment]
Maybe if I get rid of the `component.open` requirement it might work better?

**Comment by jcfranco** [comment]
Ah, my bad. I thought we weren't using since the use case above still needed to use `reposition`.

> Maybe if I get rid of the component.open requirement it might work better?

Worth exploring, IMO.

**Comment by driskull** [comment]
@benelan can you test this PR out? https://github.com/Esri/calcite-components/pull/5192

**Pull request merged**
