### PR TITLE
docs: troubleshooting type info that comes through in readmes (TESTING)

### PR DESCRIPTION
**Pull request by caripizza**
**Related Issue:** #2433 (#2241)

## Summary
WIP - I'm testing the types that come through when readme content is auto-generated from `npm run build`. I'm seeing the types correctly appear in the docs-json. However, for some reason the Storybook readme content misses these types, and just uses `any`.

### CODE REVIEW

**Comment by caripizza** [comment]
@jcfranco these are the differences I noticed in the auto-generated readmes while working on #2241. Do you know why the readmes/auto-update task isn't printing these correct types into the markdown? Should we just update them manually by merging this one in?

**Comment by jcfranco** [comment]
It could be because the auto-doc-update runs a Stencil doc build (`stencil build --docs`) and not `npm run build`.

**Comment by caripizza** [comment]
gotcha, @jcfranco can we update the action to use `npm run build` instead, so these types appear like they do in the bundle output? (I can convert issue 2433 to request that work if so.)

**Comment by caripizza** [comment]
Closing this for now, we can prioritize in the related issue since this is pretty low-hanging fruit (#2433).

**Comment by jcfranco** [comment]
@caripizza Sounds good. I still haven't been able to repro the different doc scenario. These are the steps I'm following:

1. check out local test branch (based on latest `master`)
2. run `npm run build`
3. commit readme changes
4. run `npx stencil build --docs`
5. commit read me changes

Step 5 fails after the commit is auto-linted as it ends up being identical to the existing code and bails to avoid merging an empty commit. 

On the Storybook-side of things, that doc is only updated when we release, so the auto-updating action wouldn't have any effect on it between releases. 

Let me know if I missed a step. We can also move this discussion to #2433.

**Pull request closed without merging**
