### PR TITLE
refactor(graph): updated graph default width to be 100%

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #2948

## Summary

This PR ensures the graph SVG is full width by default. Before, it would require a special data property for the chart to be full width. This has been removed.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
Code changes look good. Seems like the calcite-graph still has a width property set to 300. It seemed like the issue was more about removing those width/height properties and just making them 100% of container?

**Comment by jcfranco** [comment]
The original issue was about removing the slider-specific option for full width, but you brought up a good point. If the chart SVG occupies the full width of its container, there's no need for the `width` and `height` props, right?

**Comment by jcfranco** [comment]
@macandcheese Can you review the visual diffs? The latest changes made the histogram selection dividers narrower and now share the same width and location as the handles, which seems like an improvement, at least to my 👀 . 

basic-histogram-diff

color-histogram-diff

**Review by driskull — APPROVED** [review]
AWESOME SAUCE 🎊

**Comment by macandcheese** [comment]
These changes look good to me - cc @rmstinson @asangma for Figma update.

**Comment by jcfranco** [comment]
Current E2E failure is unrelated:

```
Summary of all failing tests
FAIL src/components/calcite-dropdown/calcite-dropdown.e2e.ts (69.154 s)
  ● calcite-dropdown › opens the dropdown with click, enter, or space › opens when dropdown-trigger is an action

    expected event "calciteDropdownOpen" to have been called 1 times, but was called 2 times

      828 |       await page.waitForChanges();
      829 |       expect(await dropdownWrapper.isVisible()).toBe(true);
    > 830 |       expect(calciteDropdownOpen).toHaveReceivedEventTimes(1);
          |                                   ^
      831 |     });
      832 |   });
      833 |

      at Object.<anonymous> (src/components/calcite-dropdown/calcite-dropdown.e2e.ts:830:35)
```

The rest of the tests and checks are ✅. Merging!

**Pull request merged**
