### PR TITLE
feat(modal): Closes modal when the outside is clicked.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #2234

## Summary

feat(modal): Closes modal when the outside is clicked and adds property disableOutsideClose to disable it. #2234

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Code LGTM!

This does change the default behavior to now close on outside clicks. @bstifle Can you confirm this is OK? This isn't specified in the original issue.

**Comment by jcfranco** [comment]
> @bstifle Can you confirm this is OK? This isn't specified in the original issue.

Actually, I was wrong, the proposed boolean in the original issue does hint at changing the default behavior. I guess there wasn't much discussion on that, so just wanted to confirm.

**Comment by driskull** [comment]
It seems like the preferred default would be to close on click. Ideally, it should do that, correct?

**Comment by bstifle** [comment]
by default yes @driskull

**Comment by bstifle** [comment]
@jcfranco  yep close when clicked outside by default!

**Pull request merged**
