### PR TITLE
build(deps): add dependency updating script

### PR DESCRIPTION
**Pull request by jcfranco**
Adds NPM script to make dependency updating easier.

Uses https://www.npmjs.com/package/updtr to update all dependencies (runs tests on each one and only updates the passing ones) and commits on success.

### CODE REVIEW

**Comment by macandcheese** [comment]
Nice! Adding a couple extra eyes to this - I'm guessing you are all using this in CAC? - are there any gotchas with not using the `update-to non-breaking` flag?

**Comment by jcfranco** [comment]
>  I'm guessing you are all using this in CAC?

Yup.

> are there any gotchas with not using the update-to non-breaking flag?

We haven't had any issues so far. `updtr` will rollback if a dependency bump causes tests to fail.

**Comment by paulcpederson** [comment]
@jcfranco not sure it's necessary to add and commit automatically as part of the script. Wouldn't I want to see what was updated before committing the change?

If we keep it, does `&&` work in windows environments now?

**Comment by jcfranco** [comment]
> not sure it's necessary to add and commit automatically as part of the script. Wouldn't I want to see what was updated before committing the change?

The intent for the script is to make routine updates easier, that's why it includes the commit. `updtr` provides a nice summary of updated dependencies after it's done. The commit can always be amended before pushing.

> If we keep it, does && work in windows environments now?

I believe so.

**Pull request merged**
