### PR TITLE
feat(tabs): animate active tab underline

### LINKED ISSUE #867: Enhancement: Tabs — add slide transition animation to active bar
Please add slide transition animation to active bar. ease-in-out. Preferably variable speed based on distance (e.g. if one tab away, .2s; if 5 tabs away .4s)

image

### PR DESCRIPTION
**Pull request by macandcheese**
**Related Issue:** Resolves #867 cc @bstifle 

## Summary
Pardon the choppy GIF:
ezgif-7-4a8bcad1525f

### CODE REVIEW

**Comment by bstifle** [comment]
Look good! 🏆

**Comment by bstifle** [comment]
image
@macandcheese

**Comment by macandcheese** [comment]
@bstifle thanks for catching, I have a couple other style fixes to add, and I'll fix this too:

- [ ] - Prevent page overflow when active tab is outside of view in a horizontally scrolling container
- [ ] - Prevent "wobble" animation lag when horizontally scrolling container is resized, or browser width is resized
- [ ] - Fix RTL location of active indicator issue when in a partially scrolled horizontal container
- [ ] - Fix hover underline position of `position=below` `calcite-tab-nav` when used without a containing `calcite-tabs` @bstifle

**Comment by macandcheese** [comment]
Still need to fix some console warnings about changing props on update, hard to trace down but once I do this should be good.

**Pull request closed without merging**
