### PR TITLE
fix(input, input-number, input-text): Fix infinite loop crashing browser. #5882

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #5882

## Summary

- Adds click handler to focus on internal inputs
- Focus handler only emits event

### CODE REVIEW

**Comment by eriklharper** [comment]
@driskull these changes look good, about the same as what I have (so far) come up with for resolving the infinite loop bug, but I still don't know how to get the `setFocus` call to work right after the programmatic insertion of the input element.  Let's sync up on this maybe tomorrow.  Focusing with the keyboard works fine, but for some reason clicks into the input don't focus the element and the `setFocus` calls don't work either.  Very strange.

**Comment by driskull** [comment]
> I still don't know how to get the setFocus call to work right after the programmatic insertion of the input element.

Yeah, I think something with focus-trap isn't allowing this. Maybe we can do this via a follow-up.

I will add a way to disable the focus trap for Modal.

**Comment by driskull** [comment]
@eriklharper can we get this one installed today?

**Review by eriklharper — APPROVED** [review]
> @eriklharper can we get this one installed today?

Yes, let's do it.  Approved :)

**Comment by geospatialem** [comment]
> I will add a way to disable the focus trap for Modal.

@driskull Do you have an open PR for the `modal` focus trap disable? Also noticed the behavior when trying to verify the related issue.

**Comment by driskull** [comment]
Yeah here's the PR: https://github.com/Esri/calcite-components/pull/5965

**Pull request merged**
