### PR TITLE
fix(modal): Allow re-opening of modal when close button is clicked

### PR DESCRIPTION
**Pull request by macandcheese**
**Related Issue:** #918 cc @noahmulfinger

## Summary
There was a discrepancy between how the modal functioned when clicking close vs. closing via Escape key. This adds a watcher to the "active" prop to sync it with the "is-active" state.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Nice! 👍

**Comment by jcfranco** [comment]
@macandcheese Ignore my comments for now. Looking at the component a little closer, I realized that my comments are related to the fact that `isActive` (state) is driving the attribute and not the `active` prop. I think this is a separate issue (API consistency).

**Review by noahmulfinger — APPROVED** [review]
Looks good to me, thanks @macandcheese!

**Comment by macandcheese** [comment]
Want to give this a quick look @paulcpederson ?

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
Nice, this is a good fix. Generally it feels weird to set an external prop from the component itself, but in this case I think it's probably warranted.

**Pull request merged**
