### PR TITLE
feat(date): add full localization support (#585, #979)

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** #585

## Summary

Part one of a multi-part pr series. This implements locale support via the translation files provided by the i18n team. Using the same approach as icon requests (ie. Mutation Observer fetches json when needed)

This enables us to simplify a lot of the wacky reverse-engineering we were previously using to parse the input value for a given locale as now we know explicitly what the separator, order, numerals are.

There is no major change in the API (other than a slight tweak of supported locales). If no locale is passed, we will first try to use the lang of the document before we fall back to english.

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]

**Review by jcfranco — APPROVED** [review]
Nice. Thanks @paulcpederson! 

Do the current date tests cover these changes? 

Other than 👆, the following comments can be tackled at a future time if they make sense:

1. Could this be refactored to use a well established 3rd-party lib (maybe a [Moment alternative](https://github.com/you-dont-need/You-Dont-Need-Momentjs)) instead of handling it ourselves?
2. Is the load-when-visible logic necessary? Unlike the icon, it seems like there wouldn't be more than a couple of date components loaded at a time.

**Comment by paulcpederson** [comment]
1. There is obviously CLDR data (which is really what we're using here) but the way it's packaged in that lib we would need to piece it together from several different files. Rather than including a large dep or having multiple requests it made more sense to utilize the i18n team and have them create something tailor made for us, IMO. Once ie11 is dropped we may be able to rework this using intl.
2. Good thought, I can remove.

**Comment by paulcpederson** [comment]
Forgot to add: there really are no e2e date tests. I inherited date with 0 testing. I've written spec tests for the utility functions, but it's on my todo to go through and write a full set of tests for calcite-date.

**Comment by jcfranco** [comment]
> Once ie11 is dropped we may be able to rework this using intl.

Sounds good. Let's revisit at that point. FWIW, some of the referenced libs use `Intl` under the hood.

On a related note, is `localeData` mostly internal? If so, we could use the `@internal` JSDoc tag to keep it in the types, but not emit any public doc for it (same for any internal APIs that may be dropped when we revisit).

**Comment by paulcpederson** [comment]
@jcfranco ok, I've added `@internal`, it's a little different as end users will likely never call these components directly. ie. `calcite-date-day` and `calcite-date-month` aren't really useful on their own (I think they are all part of one build layer as well).

**Review by jcfranco — APPROVED** [review]
15_RobertRedford_Smile
**#approvedx2**

**Comment by paulcpederson** [comment]
Thanks for all the review, y'all.

**Pull request merged**
