### PR TITLE
fix(x-close input and inline): x hover ui-text-1

### PR DESCRIPTION
**Pull request by julio8a**
**Related Issue:** #2216

## Summary

`x` on input and inline editible hover state updated to ui-text-1

### CODE REVIEW

**Comment by bstifle** [comment]
@julio8a inline editable is now ui-text-1 in all states.

should be ui-text-3 on idle.




input X is correct!

**Comment by bstifle** [comment]
@julio8a 
image
the chevrons are kinda jacked up too

**Comment by julio8a** [comment]
Bryan, as we discussed on teams, the `X` on the inline will be done in a separate branch since it needs a component change. Anything else on this one needed?

**Review by bstifle — APPROVED** [review]
lookin kln!

**Pull request merged**
