### PR TITLE
fix(alert, notice): update leading and close icons to follow calcite-action icon sizing

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #2417 

## Summary

This updates alert and notice's x and start icons as follows:

- when component scale is medium => use small scale for icons
- when component scale is large => use medium scale for icons
- when component scale is small => **no change**

**notice**

Screen Shot 2021-07-01 at 6 24 51 PM

**alert**

Screen Shot 2021-07-01 at 6 27 22 PM
Screen Shot 2021-07-01 at 6 27 57 PM
Screen Shot 2021-07-01 at 6 28 12 PM

### CODE REVIEW

**Comment by bstifle** [comment]
image


@jcfranco looks good, but would like to see both demo pages updated with examples that have actions in them if you dont mind

**Comment by jcfranco** [comment]
@bstifle Unlike notice, Alert doesn't have a specific slot for actions.

**Comment by bstifle** [comment]
gotcha gotcha.

i suppose we'll add those later with #2382

**Comment by bstifle** [comment]
@jcfranco looks like small actions are a bit off on the width

can we get these to match the X padding?

image

**Comment by jcfranco** [comment]
Sure, but that means updating calcite-action's padding for small scale globally (from sizing-2 to sizing-3). Is that OK?

**Comment by julio8a** [comment]
I think I have this in my PR for action-bar, to update the padding on action. It's the spacing between the icon and the title. Not sure if it's the same but thought I'd bring it up. 

https://github.com/Esri/calcite-components/pull/2429/files#diff-4c5550b21bcb6014dcecc11ee9b564798b1231a352538340cb9fabef70917489R110

**Comment by jcfranco** [comment]
@julio8a Thanks for bringing it up. I tested your branch and it looks like the close buttons still need to be tweaked. I synced-up w/ @bstifle and I'll be modifying the padding on the close buttons for consistency.

Before pushing, can you confirm this is the spacing we want for the small scale?

Screen Shot 2021-07-02 at 11 01 30 AM
Screen Shot 2021-07-02 at 11 01 41 AM

**Comment by jcfranco** [comment]
I forgot to add these: 

**notice**
Screen Shot 2021-07-06 at 1 46 11 PM
Screen Shot 2021-07-06 at 1 46 08 PM

**alert**
Screen Shot 2021-07-06 at 1 52 52 PM

@bstifle @macandcheese does [this change](https://github.com/Esri/calcite-components/pull/2431/commits/6ced4e0f1d6587141dad3717500881d9a0d0ec05) look good? I had to tweak the var used for the small scale that is used to pad the sides of the alert/notice to make the sizes match.

**Comment by jcfranco** [comment]
Synced up w/ @bstifle and rolled back my last change since it affected more than the close buttons. Updated the PR to only modify spacing for small scale close icons.

**Review by bstifle — APPROVED** [review]
lookin real good, waiting on screener

**Comment by jcfranco** [comment]
@bstifle I see the same spacing differences you brought up when running the storybook on master w/o my changes. Proceeding to merge based on that.

**Pull request merged**
