### PR TITLE
fix(button, split-button)!: update light, dark button colors to neutral, inverse

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** #1515

## Summary

BREAKING CHANGE: light and dark colors of buttons have been removed, replace with neutral and inverse, respectively (#1515)

@bstifle / @julio8a  can you check the split buttons on this branch and make sure those styles are desired? Can also wait for screener to report and go in and visually approve changes in there.

### CODE REVIEW

**Review by driskull — COMMENTED** [review]
This looks good but shouldn't there be changes to some tests and storybook files?

**Comment by paulcpederson** [comment]
@driskull yes, I found a couple other references that need updated as well, working on it now

**Comment by paulcpederson** [comment]
@bstifle last commit should resolve the errors running this locally

@driskull no direct references to the values in the tests, but I did update the storybook docs

**Comment by bstifle** [comment]
image

image


hey so the names are correct for dark theme,

but inverse should have ui-text-inverse border (#FFFFFF) on clear-inverse and outline-inverse.

can we get those updated?

**Comment by bstifle** [comment]
@paulcpederson  for viz

image

**Comment by paulcpederson** [comment]
Just an update, I am working with @bstifle  to slean up a lot of the button styles based on the figma doc

**Comment by paulcpederson** [comment]
rerunning jobs to see if I can get CodeQL to run, I think it got confused on a cancelled build

**Pull request merged**
