### PR TITLE
Histogram/Graph component

### PR DESCRIPTION
**Pull request by paulcpederson**
Had an idea on how to implement @bpatterson88 's  histogram design in #535 , so I gave it a shot (hope I'm not stepping on your toes @eriklharper , I think that issue is assigned to you 😬)

Essentially this pr does multiple things:
1. new `calcite-graph` component. Extremely minimal and not really for "graphing". I assume that's what calcite-charts will be. This could be used for spark lines or really reduced line graphs in the future, but for now only does area graphs.
2. uses `calcite-graph` from inside of `calcite-slider` if a data array is set on the `histogram` property. 

Screen Shot 2020-05-12 at 2 28 37 PM
Screen Shot 2020-05-12 at 2 16 09 PM

The graphs are just `svg` elements where I've generated the drawing commands manually. 
 Highlighting of the in-range section of the histogram is done by using svg masks. Essentially you draw three identical graph paths, and then point them at one of three masks (start, in-range, and end). 

This could probably be optimized further so it's not as resource-intensive on change of the slider, but I'm not really seeing that poor of performance so I didn't pursue it for now. But really you'd want to only recalculate the graph when the actual data or dimensions change. I _think_ it will be calculated on ever render right now, but this is something to look at in the future.

I didn't do any of the other features in that issue (combining handle labels, min/max labels, etc).

_side note_: If you're interested in geeking out on how the smoothing is accomplished, it uses the [Steffen method](http://adsabs.harvard.edu/full/1990A&A...239..443S) to interpolate points based on their neighbors in the data set. This is nice because the interpolation is "monotonic" and won't swing beyond the actual data points like a lot of other algorithms. I had to learn a surprising amount of math to make lines that didn't look stupid...

/cc @julio8a @bstifle

### CODE REVIEW

**Comment by bstifle** [comment]
1 and 2 sound good to me. also,

math

**Comment by eriklharper** [comment]
> 1 and 2 sound good to me. nice work. also,
> 
> math

**Comment by macandcheese** [comment]
Real strong stuff @paulcpederson. I agree a "simple" svg component for sparklines etc is a great addition.

**Comment by bpatterson88** [comment]
This looks great @paulcpederson. Appreciate the attention given to picking a good smoothing algorithm.

**Comment by macandcheese** [comment]
Get 'er in there! Only comment would be, is there a "non-smoothed" modifier available (now or in the future) to address: https://github.com/Esri/calcite-components/issues/535#issuecomment-627632967

**Comment by paulcpederson** [comment]
I think `graph` would be expanded with a `graph-type` (or `visualization`?) prop like `graphType: "area" | "line" | "bar"`  Writing the draw methods for bar and line (non smoothed) would be very simple compared to the smoothed area drawing.

**Comment by julio8a** [comment]
Since we're starting to bleed into the 'charting' conversation, we need synch up with @subgan82, as they are working on arcgis-charts

**Comment by macandcheese** [comment]
I think these will be kept to simple, svg based graphs like spark lines or quick histograms - it would be good to sync visually with whatever underlying charting library will be used for actual charts.

**Comment by subgan82** [comment]
Yes we would need to sync-up on this work  on charts in calcite-components and [arcgis-charts](https://devtopia.esri.com/WebGIS/arcgis-charts)
https://devtopia.esri.com/WebGIS/arcgis-charts/wiki/Release-and-Deployments

arcgis-charts-components are Web Components that work for feature layers and array of POJOs(inline data), this latter ability allows it to use in places where charts are needed and array of data is passed. It uses amcharts4.

**Comment by subgan82** [comment]
We can build microcharts and sparklines using amcharts. SparkLines is being requested with other web teams like Hubs , which we plan to do it after v1 release.

https://www.amcharts.com/docs/v4/tutorials/creating-sparkline-charts/

**Comment by leeoniya** [comment]
i'd advise against amcharts

https://github.com/leeoniya/uPlot#performance

**Comment by macandcheese** [comment]
Yeah, re: @leeoniya feedback, I think there's definitely a use case for very simple svg charts without adding the bloat of an external library.

**Pull request merged**
