### PR TITLE
refactor(panel): tailwindify

### PR DESCRIPTION
**Pull request by julio8a**
Supports #1677 #1500

### CODE REVIEW

**Comment by julio8a** [comment]
Screener diff is correct, from Figma, the title is bold. This one should be good to go!

CC'ing @bstifle

**Review by paulcpederson — APPROVED** [review]

**Comment by bstifle** [comment]
@julio8a 

is it using bold or Demi? ... Arent we calling demi "bold" ? (the update looks too bold)

also, looks like i messed up the summary in figma. should be text--2h.

**Comment by paulcpederson** [comment]
When we use the tailwind class `font-bold` it will set the weight to `700`, but in calcite-fonts this actually renders demi. 

The problem is that the demo pages from app-components don't include calcite-fonts, so it's probably rendering a _real_ bold. So I think you're both right, the code is correct and the screener diff is too bold.

**Comment by julio8a** [comment]
From a teams chat with Bryan and Paul, this is good to merge.

**Pull request merged**
