### PR TITLE
feat(pick-list-item): removes top margin on description

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** (#1650)

### CODE REVIEW

**Review by julio8a — APPROVED** [review]
Works for me. @bstifle?

**Comment by bstifle** [comment]
wasnt sure either on this thing

**Comment by julio8a** [comment]
@bstifle,

It shrinks down space between the title and description under it
image

gets rid of the orange bar (margin spacing).  ^

**Comment by asangma** [comment]
@julio8a Screener is showing the font-weight change you just reverted.

**Comment by asangma** [comment]
Updated with master. Awaiting tests...

**Comment by asangma** [comment]
Thanks @julio8a.
Updated and Screener test is clean now.

**Pull request merged**
