### PR TITLE
docs(calcite-checkbox): removing usage instructions for deprecated child input feature

### PR DESCRIPTION
**Pull request by eriklharper**
**Related Issue:** #874

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
👍

**Comment by paulcpederson** [comment]
@eriklharper I totally missed this, have we removed proxy input support on all the components (please say yes)?

**Comment by eriklharper** [comment]
> @eriklharper I totally missed this, have we removed proxy input support on all the components (please say yes)?

Sadly, no.  At least `date`, `switch`, `radio-group` and `radio-group-item` all still have proxy input implementations.  We can make an effort to remove these with some tickets.

I created #1096 which would remove the proxy input implementation from `radio-group` and `radio-group-item` to behave the same way as `radio-button` currently does, which was never built with proxy input support.

**Comment by paulcpederson** [comment]
Seems like a weird story that some of our components allow the proxy and some don't...

**Pull request merged**
