### PR TITLE
fix(combobox): fix stacking icon on very narrow combobox (#3891)

### PR DESCRIPTION
**Pull request by paulcpederson**
**Related Issue:** #3891

## Summary

Saw this while doing some mobile testing in another product. Using `flex-1` allows the element to scale down with no minimum, so it won't force a flex wrap.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Comment by driskull** [comment]
Can we maybe add a screener test here too?

**Comment by paulcpederson** [comment]
> Can we maybe add a screener test here too?

Does this just entail adding a story to the storybook?

**Comment by driskull** [comment]
Yeah, just a story with a squished combobox

**Comment by paulcpederson** [comment]
I think the screener failures here are mostly just the tunneling issue, so this is good to merge in my mind.

@asangma let me know if you want to change anything.

**Comment by eriklharper** [comment]
> I think the screener failures here are mostly just the tunneling issue, so this is good to merge in my mind.
> 
> @asangma let me know if you want to change anything.

I'm working right now to eliminate these tunnel failures with a static build option, but other PRs are running successful despite, so try running Screener again.

**Comment by paulcpederson** [comment]
@eriklharper do you think it's cool to merge this? Screener is showing all 400+ ui states as new but I'm not really sure how to fix it. Assuming this is related to the other screener issues?

**Comment by eriklharper** [comment]
> @eriklharper do you think it's cool to merge this? Screener is showing all 400+ ui states as new but I'm not really sure how to fix it. Assuming this is related to the other screener issues?

I re-ran the Screener job so hopefully it recognizes them as existing snapshots this time.  If not, we'll accept them and merge.

**Comment by benelan** [comment]
Looks like its down to one change now. Is that from this PR?

**Comment by paulcpederson** [comment]
@benelan yeah! I will accept it. 👍🏻

**Pull request merged**
