### PR TITLE
fix(custom-elements): add missing bundles

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This adds some missing bundles to the config and updates the `createBundles` script to warn against any missing ones.

**Question**: are there any other ones that should have a main bundle entry? The script reports the following missing ones, but not sure if they should have an independent entry: 

```
[WARNING] calcite-filter is not referenced in stencil.config.ts and will not have a bundle generated
[WARNING] calcite-graph is not referenced in stencil.config.ts and will not have a bundle generated
[WARNING] calcite-handle is not referenced in stencil.config.ts and will not have a bundle generated
```

### CODE REVIEW

**Comment by jcfranco** [comment]
@Esri/calcite-components-reviewers Can someone help review this one?

**Comment by paulcpederson** [comment]
graph is only used in slider and I think should just be part of that bundle.

**Review by paulcpederson — APPROVED** [review]

**Review by eriklharper — APPROVED** [review]
LGTM! 👍  I did have one question about `stencil.config.ts` though:  Anytime we make a new component we have to add it to the stencil config?

**Comment by jcfranco** [comment]
> Anytime we make a new component we have to add it to the stencil config?

@eriklharper Yes, it's in the conventions: https://github.com/Esri/calcite-components/tree/master/conventions#bundling-and-loading

**Comment by eriklharper** [comment]
Ah, yes it is.  I'll add those new components on my time-picker branch.

**Pull request merged**
