### PR TITLE
fix(card): fix focusing behavior when clicking on a checkbox label

### PR DESCRIPTION
**Pull request by alexabreu**
**Related Issue:** #3271

## Summary
Selection of calcite-cards is currently broken because of changes to calcite-label/calcite-checkbox. This PR restores selection of calcite cards by replacing the native `label` tag used in the component with a `calcite-label`.

### CODE REVIEW

**Comment by alexabreu** [comment]
Though I have a screener account, I don't believe I've been added to the calcite project. Can I get someone to add me? In the meantime can someone fix/tell me what needs to be fixed with the broken screener test?

**Comment by benelan** [comment]
> In the meantime can someone fix/tell me what needs to be fixed with the broken screener test?

The screener issues are unrelated to your PR, so you don't need to do anything on your end until someone gets a chance to review. Thanks for contributing!

**Comment by eriklharper** [comment]
> Though I have a screener account, I don't believe I've been added to the calcite project. Can I get someone to add me? In the meantime can someone fix/tell me what needs to be fixed with the broken screener test?

@alexabreu I just invited you to the Screener "Calcite Developers" group which will allow you to view and approve/reject screenshots on your PRs.

**Comment by caripizza** [comment]
@alexabreu yep - can you please add a pr description and clarify what this issue is fixing?

**Comment by driskull** [comment]
maybe it should be `refactor:` instead of `fix:`?

**Review by caripizza — APPROVED** [review]
LGTM! 👍  I linked the actual issue to this pr and updated the description per our current convention. Can you please add an e2e test before merging? (I included a test in the issue if you want to just use that one.)

**Comment by jcfranco** [comment]
@alexabreu Thanks for the fix! FYI, I updated the PR to describe the fix from an end-user's perspective.

**Pull request merged**
