### PR TITLE
test(block): update block demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2687 

## Summary
- update `calcite-block` demo

### CODE REVIEW

**Comment by bstifle** [comment]
@ManahariDahal looking cool. We need to add the examples with the actions in the start, and the end positions

**Comment by asangma** [comment]
@bstifle There aren't actions in the start position in Block.

**Review by asangma — CHANGES_REQUESTED** [review]
## Demo updates

- [x] Update header+control to use a CalciteAction
- [x] Update header+icon to use CalciteIcon
- [x] Add example with `collapsible` but without `control` or `header-menu-actions` content. (see below suggestion for collapsible/non-collapsible groups)
- [x] Add example with both `control` and `header-menu-actions`
- [ ] Add example with default BlockSection (i.e. without setting `toggleDisplay`)
- [ ] Update BlockSection content to use perhaps some Label and Input combos but something more realistic than the placeholder images.

## Some suggestions
Not required but could be nice.

Suggest adding a group for `collapsible` and a group without `collapsible`.
This will demonstrate the behavioral differences.

Also might be good to show the non collapsible Blocks open with some "normal" content in them, e.g. some labels and inputs.

**Comment by ManahariDahal** [comment]
@asangma how does this look?

**Comment by asangma** [comment]
@ManahariDahal Thanks for the ping. 👀

**Review by asangma — APPROVED** [review]
Looking great! Thanks for the updates.

**Review by julio8a — APPROVED** [review]
Looks good!

**Review by bstifle — APPROVED** [review]
Lookin Good!

**Pull request merged**
