### PR TITLE
test(accordion): updated accordion demo

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2616 

## Summary
- updated `calcite-accordion` demo page

### CODE REVIEW

**Comment by driskull** [comment]
@jcfranco seems like we have an unstable color picker test.

```
FAIL src/components/calcite-color-picker/calcite-color-picker.e2e.ts (293.017 s)
  ● calcite-color-picker › emits event when value changes
    expected event "calciteColorPickerInput" to have been called 9 times, but was called 11 times
      225 | 
      226 |     expect(changeSpy).toHaveReceivedEventTimes(6);
    > 227 |     expect(inputSpy).toHaveReceivedEventTimes(9);
          |                      ^
      228 | 
      229 |     // change by dragging hue slider thumb
      230 |     const [hueScopeX, hueScopeY] = await getElementXY(page, "calcite-color-picker", `.${CSS.hueScope}`);
      at Object.<anonymous> (src/components/calcite-color-picker/calcite-color-picker.e2e.ts:227:22)
          at runMicrotasks (<anonymous>)
```

**Comment by jcfranco** [comment]
I just saw this in another PR as well. 😞  I'll create an issue to stabilize and skip it.

**Comment by jcfranco** [comment]
https://github.com/Esri/calcite-components/issues/2694

**Comment by bstifle** [comment]
heyyyyy, can we do something more like this with a 3 column layout?:

image

**Review by julio8a — DISMISSED** [review]
Update to Bryan's mockup

**Review by ManahariDahal — COMMENTED** [review]
updated to Figma

**Review by bstifle — APPROVED** [review]
Looking great! 🥈

**Review by julio8a — APPROVED** [review]
Thanks for the updates! Looks good

**Pull request merged**
