### PR TITLE
refactor(select): Match Figma and Tainwindify

### PR DESCRIPTION
**Pull request by julio8a**
**Related Issue:** #1500

## Summary

- First pass at matching Figma

Working from the [Figma/Tailwind components refactor project](https://github.com/Esri/calcite-components/projects/14)

Project card: https://github.com/Esri/calcite-components/projects/14#card-60667918

### CODE REVIEW

**Comment by bstifle** [comment]
ok this is looking really good! except for RTL:

image


the chevrons should be on the left side i believe

**Comment by julio8a** [comment]
I had pushed this fix up, might need to pull down the latest commits. If not try resetting your branch.

**Review by bstifle — APPROVED** [review]
looks good

**Comment by julio8a** [comment]
@jcfranco or @driskull this one could use a dev review too.

**Review by driskull — APPROVED** [review]
👍

**Pull request merged**
