### PR TITLE
refactor(tailwind): extract tailwind preset

### PR DESCRIPTION
**Pull request by jrowlingson**
**Related Issue:** https://github.com/Esri/calcite-components/issues/6602

## Summary

This also bumps tailwind to v3.3.1.

### CODE REVIEW

**Comment by mpriour** [comment]
I really like this idea. It does give end users an easy way to incorporate our styling without having to manually mesh our tailwind config with theirs.

**Comment by jcfranco** [comment]
Awesome! Thanks for extracting the config into its own preset. We are planning to distribute the config in its own package once the design tokens are ready and applied to the config. From that perspective, I'd like to hold off on including the preset as part of the `calcite-component`'s package, but we can move forward installing the preset extraction. cc @alisonailea

**Comment by jrowlingson** [comment]
Thanks for taking a :eyes:, I've removed the preset from inclusion in the package.

**Comment by jcfranco** [comment]
@jrowlingson Awesome. I'll help adopt this PR and get it installed this week. Thanks again! 🎉

**Pull request merged**
