### PR TITLE
test(rating): updated calcite-rating demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2536 

## Summary
- match the current calcite-rating demo page according to the Figma design
- _small_, _medium_, and _large_ variants included

### CODE REVIEW

**Comment by bstifle** [comment]
looking pretty good!

image

some issues with the above. what is "chip combinations?" (no chips visual)
these labels... 
image
color seems off. is this using calcite-label?

**Comment by ManahariDahal** [comment]
> looking pretty good!
> 
> image
> 
> some issues with the above. what is "chip combinations?" (no chips visual)
> these labels...
> image
> color seems off. is this using calcite-label?

Yes, the text is basically inside _calcite-label_, weird that it failed

**Comment by bstifle** [comment]
@ManahariDahal 

image

label is still funky on the demo

**Review by bstifle — APPROVED** [review]
noice

**Review by julio8a — APPROVED** [review]
LGTM!

**Pull request merged**
