### PR TITLE
feat(shell-center-row): remove CSS transition for height

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #1554

## Summary
Removes CSS transition for height.
While it's nice to have, the transition can cause rendering issues with the "micro apps" it contains.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Comment by asangma** [comment]
cc @nel11211

**Comment by asangma** [comment]
Thanks @driskull

**Review by nel11211 — APPROVED** [review]
👍

**Comment by asangma** [comment]
@driskull this seems to have the same build thing as #1564.

**Comment by driskull** [comment]
@asangma Yeah we got some unstable tests it seems.

**Comment by asangma** [comment]
Thanks @driskull. 👊

**Pull request merged**
