### PR TITLE
fix(button): fixes missing text-alignment for alignment prop.

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #1562 

## Summary
Especially when using `icon-start-space-between` or `icon-end-space-between`, wrapped text would reveal itself to be centered causing weird looking layout.

This fixes that.

Before
image

After
image

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
I'm all for anything that removes centered text as a general rule.

**Comment by driskull** [comment]
We have a broken test with the combobox and a ton of warnings we need to cleanup in the build :(

**Comment by paulcpederson** [comment]
@driskull  Travis CI output linked above doesn't have any errors re:combobox that I can see. 
From what I see it looks like a missing APIKey, @eriklharper may know more about that (screener related?). 

The mutable props warning are super annoying though, agree on that

**Comment by driskull** [comment]
ok. I saw the test fail on one of Alan's branches. https://github.com/Esri/calcite-components/pull/1563 . https://travis-ci.com/github/Esri/calcite-components/builds/217303805 .

Opened PR to get rid of these warnings: https://github.com/Esri/calcite-components/pull/1565

**Comment by asangma** [comment]
Thanks y'all. I'll mergle the recent build update into this and push.

**Comment by asangma** [comment]
Should I ignore the Travis errors on this one or wait? 😬

**Comment by driskull** [comment]
@asangma we can merge. But we need to get screener fixed eventually. @eriklharper can you look into it?

**Comment by eriklharper** [comment]
I noticed the apiKey problem on a branch of mine also, and in the past that was caused by pull requests being initiated from a forked repository (forked repos don't have permission to access Travis environment variables).  Not sure what it now causing this to show up when clearly this PR is not from a forked repo.  I'll ask Loyal about this as well, as there is also some false positives I've been noticing on some of mine and others PRs too.

**Comment by eriklharper** [comment]
Looks like the build triggered on travis-ci.ORG, which for some reason doesn't have the screener api key defined.  I just added it and restarted the build to make sure this works even though it is merged.

**Comment by asangma** [comment]
Thanks!

**Pull request merged**
