### PR TITLE
fix(input): Support default value to reset an input

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1507

## Summary

fix(input): Support default value to reset an input

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
Nice! Can you add an automated test for this before merging?

**Review by jcfranco — APPROVED** [review]
👍

**Comment by driskull** [comment]
@eriklharper and @macandcheese can you give this a glance?

**Review by macandcheese — APPROVED** [review]
Thanks!

**Comment by eriklharper** [comment]
LGTM

**Pull request merged**
