### PR TITLE
fix(switch): provide a selected color to track element (#3987)

### PR DESCRIPTION
**Pull request by mpriour**
* Use canvasText system color to show selected state of switch control. This color matches the normal text color, outlines, and borders in high contrast mode

**Related Issue:** #3987

## Summary
Fix provides a color to the switch track when the control is selected.
high contrast switch with canvasText color

### CODE REVIEW

**Comment by mpriour** [comment]
@macandcheese Can you approve this PR, or does it still need more work?

**Review by macandcheese — APPROVED** [review]
Thanks for adding @mpriour !

**Comment by benelan** [comment]
I got the PR to pass screener, is this ready to merge @mpriour?

**Comment by mpriour** [comment]
Good to go. Thanks.

**Pull request merged**
