### PR TITLE
refactor(filter): drop deprecated + undocumented prop and event payload

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This PR is a follow-up from https://github.com/Esri/calcite-components/issues/2208#issuecomment-963767923.

### CODE REVIEW

**Comment by jcfranco** [comment]
Modified milestone to install after December release.

**Review by driskull — APPROVED** [review]
🧹 ✨ 👍

**Comment by jcfranco** [comment]
cc @benelan

**Pull request merged**
