### PR TITLE
fix(tip): Hide tip when dismissed.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** None

## Summary

fix(tip): Hide tip when dismissed.

Currently, closing the tip still shows the close button and border.

https://esri.github.io/calcite-components/?path=/story/components-app-tip--basic

### CODE REVIEW

**Comment by driskull** [comment]
For things like this, it might be best if we didn't apply styling on the host. Since those styles can be modified by the user, a user could override the display:none styling.

**Comment by driskull** [comment]
I can haz merge?

**Comment by driskull** [comment]
@jcfranco can you review?

**Review by jcfranco — APPROVED** [review]
Awesome!

**Pull request merged**
