### PR TITLE
test(notice): updated demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2611 

## Summary
- updated demo page
- _small_, _medium_, and _large_ variants included

### CODE REVIEW

**Comment by bstifle** [comment]
@ManahariDahal 

The labelling is a little strange with this new layout.

Can we do the props/labels in this order in all 3 sizes?:
image

**Review by julio8a — APPROVED** [review]
This looks good to me!

**Comment by julio8a** [comment]
I'm good with Bryan's suggestions

**Review by bstifle — APPROVED** [review]
YAS! nice one

**Pull request merged**
