### PR TITLE
✨ Loader improvements

### PR DESCRIPTION
**Pull request by paulcpederson**
1. Converted to circle
2. Works in edge
3. Works in ie11
4. Determinate loader has new fade-out on completion
5. No more `requestAnimationFrame` js stuff for edge 

In IE and Old Edge the segments are rotated, but in more modern browsers the dash-array is animated. The dash-array animation is slightly sharper, so for machines that can handle it I've left it.

@julio8a @bstifle I've also added a [series of variables](https://github.com/Esri/calcite-components/pull/384/files#diff-a3b65abeb0b9258c91de75281e64c75bR17-R25) that act as knobs letting you easily tweak the animation if you want to run this locally and change numbers until it looks right.

@macandcheese I think we can close the other loader pr that is currently open after this? IDK let me know

### CODE REVIEW

**Comment by bstifle** [comment]
👀

**Comment by macandcheese** [comment]
Awesome! Yeah we can close the other one. From a system question my ask would be - do we want that many "knobs", or anything at all besides maybe color, to be changed?

Maybe just remove those after @bstifle does his thing?

**Comment by bstifle** [comment]
@paulcpederson hey man! looking pretty awesome.

Determinate is beautiful, nice work.

Over all the big indeterminate ones seems to be a litttttle slow. Almost like they can increase by 20-30% speed.

I think the speed problem is most pronounced on the little inline one. I almost feels like that slow Chrome loader when a page is about to timeout. I think the inline one could probably be 50-60% faster

**Comment by bstifle** [comment]
i think "loading text" should have some more margin between the loader and text. maybe 20px more

**Comment by paulcpederson** [comment]
@macandcheese the "knobs" are not available to other devs, they are internal only. The only things that can be customized are the colors via overriding the global theme

**Comment by macandcheese** [comment]
Yeah, edited my comment I misunderstood your comment in pr :)

**Comment by paulcpederson** [comment]
cool, @bstifle I will try to tack on another commit onto this pr with those tweaks when I get a second :+1:

**Comment by paulcpederson** [comment]
Timing updated. I think this is ready to go in, thoughts @macandcheese ?

**Comment by macandcheese** [comment]
Looks great, the fade out is a nice touch!

**Comment by bstifle** [comment]
@paulcpederson  Looks awesome. ship it. thanks paul!

**Comment by bstifle** [comment]
@paulcpederson will you be updating the padding on the loading text thing? or is that meant to be just bare styling as a placeholder?

**Comment by paulcpederson** [comment]
@bstifle oh, no I just missed that comment, can update today prior to merge

**Comment by bstifle** [comment]
dope thanks @paulcpederson !

**Pull request merged**
