### PR TITLE
refactor(notice): Tailwind and Figma match

### PR DESCRIPTION
**Pull request by julio8a**
**Related Issue:** #1500

## Summary

- Utilize tailwind
- Match figma designs

Working from the [Figma/Tailwind components refactor project](https://github.com/Esri/calcite-components/projects/14)

Project card: **Related Issue:** #1500

## Summary

- Added all sizes to the demo page
- First pass at matching Figma

Working from the [Figma/Tailwind components refactor project](https://github.com/Esri/calcite-components/projects/14)

Project card: https://github.com/Esri/calcite-components/projects/14#card-60667723

### CODE REVIEW

**Comment by bstifle** [comment]
@julio8a 

Hard to say on this one. Can we add small medium and large variants, and then some margins on the view? this is what i see:

image

**Comment by julio8a** [comment]
Maybe try clearing the cache. The sizes should show up right above the dark theme components

image

**Comment by bstifle** [comment]
oh man i'm so blind. they are there!


ok so!
Only fix would be using 16px icons for small scale (left icon and X):

### Build:
image

### Design:
image

**Comment by julio8a** [comment]
@bstifle, Just pushed that up, ready for review!

**Review by bstifle — APPROVED** [review]
latest looks dope!

**Pull request merged**
