### PR TITLE
test(color): restore skipped color input tests

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #928 

## Summary

A [recent change](https://github.com/Esri/calcite-components/pull/1054) to the CI environment (thanks @paulcpederson!) stabilizes e2e tests and the color input ones are now running smoothly. 🧈

### CODE REVIEW

**Comment by paulcpederson** [comment]
oh nice!

**Comment by jcfranco** [comment]
I did quite a few test runs and all color input tests are passing. This build failed a couple of times on the following, unrelated, test:

```
  ● calcite-date › fires a calciteDateChange event when changing year in header
    TypeError: Cannot read property 'callMethod' of null
      36 |     const input = await page.find("calcite-date >>> calcite-input");
      37 |     const changedEvent = await page.spyOnEvent("calciteDateChange");
    > 38 |     await input.callMethod("setFocus");
         |                 ^
      39 |     // have to wait for transition
      40 |     await new Promise((res) => setTimeout(() => res(true), 200));
      41 |     // can't find this input as it's deeply nested in shadow dom, so just tab to it
      at Object.<anonymous> (src/components/calcite-date/calcite-date.e2e.ts:38:17)
          at runMicrotasks (<anonymous>)
```

cc @paulcpederson

**Comment by paulcpederson** [comment]
@jcfranco weird, that passes for me. Is it just broken on travis, or is it failing locally as well?

**Comment by jcfranco** [comment]
It's failing once in a while on Travis.

**Comment by paulcpederson** [comment]
trying out another strategy to fix it, but IMO, you should just merge this as it's not causing the issue.

**Review by paulcpederson — APPROVED** [review]

**Pull request merged**
