### PR TITLE
feat(slider): update disabled style 

### PR DESCRIPTION
**Pull request by asangma**
re #676

### CODE REVIEW

**Comment by macandcheese** [comment]
Looks good to me if you want to move it out of draft ✅

**Comment by asangma** [comment]
Thanks @macandcheese!

**Comment by asangma** [comment]
cc @zaramatheson

**Comment by bstifle** [comment]
yeah gray the graph!

**Comment by asangma** [comment]
I looked at that. It is part of the SVG, but i'll look at the TSX.

**Comment by asangma** [comment]
@bstifle @macandcheese Updated, y'all.

**Comment by macandcheese** [comment]
Awesome, maybe in the future we can add a `disabled` prop to `calcite-graph` and then set that within `calcite-slider` - but since this is the only place `calcite-graph` is being used I think this is fine for now! Thanks @asangma

**Comment by asangma** [comment]
No problem. Murge?

**Pull request merged**
