### PR TITLE
fix(dropdown): revert dropdown-trigger-container width 

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** (#2625)

## Summary
One line change to rule them all.
Reverts trigger width to 100%.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Comment by asangma** [comment]
Thanks @driskull 
Discovered why the width: 100% was removed, i.e. SplitButton.
Updated to use flex stuff instead of width: 100%.

**Review by driskull — APPROVED** [review]
👍

**Comment by asangma** [comment]
Thanks man!

**Pull request merged**
