### PR TITLE
fix(panel, shell-panel): flex grow, shrink, basis definitions 

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** (#1914)

## Summary
Adds explicit flex grow, shrink, and basis definitions to make Safari play nice.

cc @AdelheidF 
Also added to Panel at the :host level to ease integration.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
Looks good. Do we need a test?

**Comment by asangma** [comment]
@driskull I don't think so since it's not property dependent and mostly just makes an explicit CSS style for what Chrome does by default.

**Comment by asangma** [comment]
Unless you mean a Screener test?

**Review by driskull — APPROVED** [review]
👍

**Pull request merged**
