### PR TITLE
chore: add changelog preview script

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This adds the following NPM scripts to generate changelog previews:

* `previewChangelog` - generates the entire changelog
* `previewChangelog:latest` - generates a changelog based on the previous release

### Notes

* Changelog generation is powered by [`standard-version`](https://github.com/conventional-changelog/standard-version/) 
* ☝️ expects release tags to be on `master`. If this is not the case, the commit compare URL will be wrong and the changelog may include entries from previous releases, so always double check. For example, note the commit range for the **1.0.0-beta.37 link**:

```
# Changelog

This document maintains a list of released versions and changes introduced by them.
This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)

<!--                                                     always check the commit range here 👁👇  -> 
## [1.0.0-beta.37](https://github.com/Esri/calcite-components/compare/v1.0.0-beta.35...v1.0.0-beta.37) (2020-08-11)

### ⚠ BREAKING CHANGES

* **shell-panel:** `detachedScale` is now `heightScale`

### Features

* **color:** add appearance property to support embedded use cases ([#776](https://github.com/Esri/calcite-components/issues/776)) ([3598bbe](https://github.com/Esri/calcite-components/commit/3598bbe29da779bab6962fa6f343c69bbac80744)), closes [#750](https://github.com/Esri/calcite-components/issues/750)
...

### Bug Fixes

* **calcite-checkbox:** cleaning up hidden input when checkbox is unmo… ([#813](https://github.com/Esri/calcite-components/issues/813)) ([2bc35e8](https://github.com/Esri/calcite-components/commit/2bc35e8022f9295c190e99381b2a490e8152e0fc))
...
```

* This also has a script hook that will prevent releasing from a non-`master` branch.
* This ports the changelog-generating scripts from `calcite-app-components`, with `ensureNonPrereleaseChangelog` updated to include changes between prereleases and having `standard-version` use the `--prerelease` flag.

### CODE REVIEW

**Comment by driskull** [comment]
I think we'll need to remove this as it's not really a breaking change:

```
### ⚠ BREAKING CHANGES

* **shell-panel:** `detachedScale` is now `heightScale`
```

**Comment by jcfranco** [comment]
@driskull Good catch. Yeah, for now, we'll have to manually tweak entries, but it should be smoother now.

**Comment by paulcpederson** [comment]
Can we update `CONTRIBUTING` so that the pre-flight checklist for releasing has steps for using this tool?

**Comment by jcfranco** [comment]
Done. Can you review? https://github.com/Esri/calcite-components/pull/843/commits/a63c3221e6ec0a7e349318aad123a1213013bae0 

We can drop the ⚠️ note when I update the release scripts.

**Comment by paulcpederson** [comment]
Nice, thanks @jcfranco !

**Pull request merged**
