### PR TITLE
fix(dropdown): Provide context to dropdown item selections when closing the menu for screen reader users

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #4866

## Summary

fix(dropdown): Provide context to dropdown item selections when closing the menu for screen reader users (#4866)

### CODE REVIEW

**Comment by driskull** [comment]
@geospatialem could you test this out?

**Comment by geospatialem** [comment]
> could you test this out?

@driskull It seems to be functioning the same for VO, NVDA, and JAWS with no feedback when the menu closes after selection. ☹️

**Comment by driskull** [comment]
@geospatialem can you test again?

**Comment by geospatialem** [comment]
Its much easier to navigate - now its announcing when its collapsed (which is a fantastic improvement). 

Will take a peek tomorrow to see if the great enhancements you added make it easier to announce the item when its selected and the menu is collapsed.

**Comment by driskull** [comment]
Ok if we need to do this then we need to rethink how the slotted dropdown trigger works. 

If a `button` is slotted into this component and the "menu" is also a button then aXe will complain about nested button roles.

Ideally, anything a user would slot as a trigger would not be a button so that there are no nested button roles. cc @jcfranco @benelan. Whatever the user clicks should only toggle the menu and not do anything else anyway.

**Comment by driskull** [comment]
```
Summary of all failing tests
FAIL src/components/dropdown/dropdown.e2e.ts (86.621 s)
  ● calcite-dropdown › is accessible

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('calcite-dropdown,#calcite-dropdown-e33cd73c-bbaf-faab-d0af-93bfc9decc28-menubutton') to have no violations:

    <div aria-controls="calcite-dropdown-e33cd73c-bbaf-faab-d0af-93bfc9decc28-menu" aria-expanded="false" aria-haspopup="menu" class="calcite-dropdown-trigger-container" id="calcite-dropdown-e33cd73c-bbaf-faab-d0af-93bfc9decc28-menubutton" role="button"><slot name="dropdown-trigger"></slot></div>

    Received:

    "Interactive controls must not be nested (nested-interactive)"

    Fix any of the following:
      Element has focusable descendants

    You can find more information on this issue here: 
    https://dequeuniversity.com/rules/axe/4.4/nested-interactive?application=axeAPI

      65 |       getTag(componentTagOrHTML)
      66 |     )
    > 67 |   ).toHaveNoViolations();
         |     ^
      68 | }
      69 |
      70 | /**

      at accessible (src/tests/commonTests.ts:67:5)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (src/components/dropdown/dropdown.e2e.ts:934:5)
```

**Comment by geospatialem** [comment]
This looks to be the expected behavior of the `role="menu"`, since its collapsed, screen readers provide context the menu is now collapsed, rather than an item was selected since its the primary focus. In adding a `setTimeout` function prior to closing the menu, the selection is heard, so my guess is there is an assertive tag associated with the closing of the menu, that ignores that a selection has taken place. For context, [the role only needs to convey elements within the menu](https://a11ysupport.io/tech/aria/menu_role), not necessarily whether they are selected/not selected.

If we modified the roles to `listbox` (and set `aria-multiselectable="true"` for multi selection mode and "false" for the other selection types) and `option` , we'd get the results for the intent back to screen readers, but that's a much more major overhaul.

Some possible options as we move forward:
1. No code changes. Instead provide documentation that to support assistive technologies, we recommend setting the `disableCloseOnSelect` to provide on-demand feedback to assistive technologies on `dropdown-item` select.
2. Change the `disableCloseOnSelect` to be true by default to provide support to assistive technologies. The property could still be set to false, for those seeking to disable it, but the documentation could indicate the lack of support to assistive technologies.
3. Update the roles, possibly to `listbox`, or another alternative role, to provide on-demand feedback to assistive technologies.
4. TBD?

**Comment by driskull** [comment]
I think this issue is blocked until we can resolve the nested button issue.

**Pull request closed without merging**
