### PR TITLE
Fix for issue 692

### PR DESCRIPTION
**Pull request by ffaubry**
#692

### CODE REVIEW

**Comment by ffaubry** [comment]
This is my first PR for this repo/team.
Requested Adam's review.

**Comment by driskull** [comment]
@ffaubry do you think you could make the same change for the tooltip manager?

**Comment by macandcheese** [comment]
LGTM - thanks @ffaubry

**Comment by ffaubry** [comment]
@driskull I can.
I don't see any tests for tooltip?

**Comment by driskull** [comment]
@ffaubry should be here: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tooltip/calcite-tooltip.e2e.ts

**Comment by ffaubry** [comment]
@driskull Made the changes. Please review again. Thx

**Comment by driskull** [comment]
Thanks!

**Pull request merged**
