### PR TITLE
fix(action): updates line-height and affected y padding

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** (#3955)

## Summary
Updates line-height and reduces y-padding to accommodate increased height of text container.

### CODE REVIEW

**Comment by macandcheese** [comment]
LGTM - how can we communicate these changes to Figma design team (not unique to this, but any issue that could affect Figma instance)? 

@asangma we don't need this change on scale L?

**Comment by asangma** [comment]
@macandcheese I think the sizing should be the same in Figma. 

re: scale L
It appears that the increased line-height isn't affecting the height of large actions.
In M and S the text container increases in size, hence the block padding updates for those scales.

**Comment by asangma** [comment]
> Could this issue be reproduced in our storybook? 

@jcfranco I believe the issue would occur for Arabic. So I would add a test with the language set as such yeah?

**Comment by jcfranco** [comment]
> So I would add a test with the language set as such yeah?

Correct. [Here’s](https://github.com/Esri/calcite-components/blob/master/src/components/input-time-picker/input-time-picker.stories.ts#L71) an example.

**Comment by asangma** [comment]
Thanks @jcfranco

**Comment by eriklharper** [comment]
@asangma that's such a miniscule diff that I would ignore that for now and just accept the changes.  From the looks of it, neither screenshot looks ideal since the hyphen appears to close to the left-most number, so it is probably worth taking a look at why that's specifically occurring in slider in a separate issue.  It could also be just present on Chrome 87 and maybe it looks fine in the latest browser versions too.

**Comment by asangma** [comment]
Hurm...the e2e failure seems to be coming from Filter?

```
calcite-filter › filter behavior › updates filtered items after filtering
```

**Pull request merged**
