### PR TITLE
fix(value-list-item): change to older tailwind class for outlining a selected item

### PR DESCRIPTION
**Pull request by y0n4**
**Related Issue:** #3877 

## Summary
The new tailwind class `ring` was created in effort to replace the `shadow` class. However the ring class currently has several new custom tailwind properties (ex, `--tw-ring-inset`, `--tw-ring-offset-width`, `--tw-ring-color`) that are not visible when rendered. 

There seems to be an issue with the ring class specifically. Found [here](https://github.com/tailwindlabs/tailwindcss/discussions/7129) and [here](https://github.com/tailwindlabs/tailwindcss/issues/6328). For now just going to go back to using the shadow class just for outlining a selected item.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
LGTM! 🎉

Can you update the description and link to the Tailwind v3 issues you found? We should also create a follow-up issue to restore `ring` when fixed.

**Comment by jcfranco** [comment]
cc @driskull @macandcheese

**Comment by driskull** [comment]
Just keep in mind this: https://v2.tailwindcss.com/docs/upgrading-to-v2#replace-shadow-outline-and-shadow-xs-with-ring-utilities

**Review by driskull — APPROVED** [review]
👍 

Looks good. We just gotta upgrade it at some point.

**Pull request merged**
