### PR TITLE
style dropdown group text

### PR DESCRIPTION
**Pull request by paulcpederson**
Styled the combobox group text with border, etc so it looks more like dropdown group.

@driskull opening this onto your branch feel free to close if you are going a different direction.

### CODE REVIEW

**Comment by driskull** [comment]
Thanks @paulcpederson. Can you resolve the conflicts? I tried my best to style it.

**Comment by paulcpederson** [comment]
@driskull so you want these titles to be at multiple levels?

**Comment by driskull** [comment]
@paulcpederson I was thinking yes since they are capable of nesting.

**Comment by paulcpederson** [comment]
@driskull ok that's what I was thinking. We should run it by Bryan and Alan

**Review by driskull — APPROVED** [review]
@paulcpederson looks good. Lets merge it 👍

**Comment by driskull** [comment]
Thanks Paul!

**Pull request merged**
