### PR TITLE
feat(chip): add support for closed prop

### PR DESCRIPTION
**Pull request by anveshmekala**
**Related Issue:** #4826 

## Summary

This PR will add support for `closed` prop on `calcite-chip` which hides the chip element when set to true.

### CODE REVIEW

**Comment by anveshmekala** [comment]
> **Related Issue:** #4826
> 
> ## Summary
> This will remove the `calcite-chip` element from DOM when the user clears the chip using the close button.

adding `closed` property isn't necessary considering the only time chip can be closed is when the `closable` prop is set to true and the user clicks on the close icon. 

If we have a use case where the user didn't set the `closable` prop and yet wants to hide and display an icon based on some user interaction then yes we may need `closed/open` prop.

**Comment by benelan** [comment]
> adding `closed` property isn't necessary considering the only time chip can be closed is when the `closable` prop is set to true and the user clicks on the close icon.

I disagree, I think we should add a `closed` property for when a chip needs to be displayed again after clicking the "x" on closable elements. Otherwise it has to be completely re-added to the DOM like Matt is saying

**Comment by driskull** [comment]
Ben summed it up! hit the nail on the head. 🔨

**Comment by benelan** [comment]
multi selection comboboxes will need a refactor after adding the `closed` prop

**Pull request merged**
