### PR TITLE
test(tabs): updated tabs demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2640 

## Summary
- updated `calcite-tabs` demo page
- small, medium and large variants included

### CODE REVIEW

**Comment by bstifle** [comment]
pretty good!

couple things:
image

1. can we expand the column widths for these so they dont scroll?
image
2. We need a bordered position bottom version
3. Would be nice to have 3 items in each example, instead of 2

**Review by julio8a — APPROVED** [review]

**Comment by caripizza** [comment]
Why are we removing the cookie and programmatically changing the active tab examples? Are these already covered in e2e tests?

**Comment by bstifle** [comment]
@ManahariDahal can you add the position bottom version of this?
image

**Review by bstifle — APPROVED** [review]
Nice one! 1️⃣

**Pull request merged**
