### PR TITLE
test(heights): adds demo page for manually spot-checking component heights together

### PR DESCRIPTION
**Pull request by caripizza**
**Related Issue:** n/a (This came out of the button refactor draft pr branch I'm working on)

## Summary
Adds a new src/demos/height/height.html page based on @bstifle mockup for comparing component heights in each scale (to help with the Figma refactor effort).

MicrosoftTeams-image (9)

### CODE REVIEW

**Comment by bstifle** [comment]
@caripizza 
this is nice!

image


i think we should kill all the shadows, and possibly change the background to ui-background

**Comment by bstifle** [comment]
@caripizza lookin cool!

What do you think if we had a swtich to turn on/off a horizontal grid?

image

**Comment by caripizza** [comment]
@bstifle I like it! I'll add 👍

**Review by julio8a — APPROVED** [review]
This is very helpful! Nice add Cari.

**Pull request closed without merging**
