### PR TITLE
refactor(radio-group, radio-group-item): match Figma heights

### PR DESCRIPTION
**Pull request by caripizza**
**Related Issue:** #2041

## Summary
Updates the calcite-radio-group large height to 2.75rem (44px), and ensures the height for vertically stacked calcite-radio-group-items match the horizontal layout height.

### CODE REVIEW

**Comment by caripizza** [comment]
@julio8a or @bstifle this one is ready for you guys to check out (opened as draft for Screener)

**Comment by julio8a** [comment]
[Jumping in Bryan's shoes]

Very nice, these are looking great!
Reference: light gray bg is implementation, white bg is Figma design
image

The vertical layout matches perfectly when overlapped. 
image

## Outstanding differences:
#### radio button label (all scales):
- On Figma, text color is ui-text-1


#### horizontal spacing:
- There is a 1px difference in spacing on the horizontal layout:
image

Spacing between radio-buttons is spacing.4 (24px)
image

There is 1px spacing between the container and the text, so this might be okay?
image


Everything else LGTM

**Comment by caripizza** [comment]
Thanks @julio8a! Is the font color difference you're describing coming from calcite-label? Do you want me to update that on this one or just focus on the spacing difference instead?

**Comment by julio8a** [comment]
If it's coming from calcite-label, my preference when using a component within another is to not change anything. 

CC'ing @bstifle  to get his input on the difference. 

On the spacing, is it more of a Figma bug? because of the 1px spacing in the text container?

**Comment by bstifle** [comment]
@caripizza are the radio buttons using calcite-label for the text in each item?

The 1px spacing difference is fine. Probably just the text. The vertical space is more important to match

**Comment by caripizza** [comment]
> @caripizza are the radio buttons using calcite-label for the text in each item?

Yep - each radio button in the demo pages is nested in a calcite-label (which adds the font color based on the label status)

**Comment by caripizza** [comment]
This one's ready for re-review. Main changes are: updated large calcite-radio-group to 44px, ensures individual calcite-radio-group-items match the new spacing scale (24,32,44). (Also updated demo html to clarify longer text in radio-group-items should not wrap.)

**Comment by caripizza** [comment]
Actually, what is `width="full"` on calcite-radio-group supposed to do? Is it supposed to function like calcite-button's width attribute? (i.e., should the radio-group fill a set-width container when the group's width is set to "full", and not fill the whole width when set to "auto"?)

**Comment by caripizza** [comment]
This one needs a code-review

**Comment by caripizza** [comment]
@bstifle @julio8a I'm sorry for the run around on this one! I nixed the changes to radio-button-group in this pr for clarity sake. Instead, I focused on making sure radio-group/radio-group-item heights match Figma (also added `medium` font weight to the group).

**Review by julio8a — APPROVED** [review]
LGTM!

**Comment by bstifle** [comment]
ok ok ok.

One last thing. Can we get the type and the radio ellipses centered vertically?

image

**Comment by julio8a** [comment]
alignment: I'm wondering if this was fixed in the code you had before @caripizza. When I overlaid the Figma screenshot over the code, everything was perfectly aligned. [see here](https://github.com/Esri/calcite-components/pull/2710#pullrequestreview-722717955)

**Comment by caripizza** [comment]
@bstifle @julio This pr is for nailing down the Figma styles for radio-group and radio-group-item - let's address radio-button-group and radio-button styles in a different pr.

I just updated the margins for radio-group-item icons per Figma - and stopped using the radio-group's min-heights for each scale. One thing I'm not sure about is the `:focus` behavior. Should we match button with the blue outline when an item is selected? Or which one needs to change?

**Comment by bstifle** [comment]
this PR is a little misleading too. cuz radio group is the rectangular-based component haha! .............. is that the case? cuz im only seeing conversation about Radio Button Group

@caripizza

**Comment by bstifle** [comment]
@caripizza " I nixed the changes to radio-button-group in this pr for clarity sake."

just read that. dang it. ok i'll look at the actual component we should be reviewing my bad

**Comment by julio8a** [comment]
My mistake too, my initial review was on radio-button and radio-button-group. It should have been radio-group and radio-group-item. 

Those components are just so confusing with the naming. radio-group and radio-group-item look good to me. 👍

**Comment by julio** [comment]
> @bstifle @julio This pr is for nailing down the Figma styles for radio-group and radio-group-item - let's address radio-button-group and radio-button styles in a different or.

different @julio :p

**Pull request merged**
