### PR TITLE
fix(avatar): Updated large avatar to match design

### PR DESCRIPTION
**Pull request by bpatterson88**
**Related Issue:** #2041

## Summary

Updated large avatar font size to 16px (font-0).

### CODE REVIEW

**Comment by jcfranco** [comment]
@bpatterson88 When you merge, can you make sure the commit title message is the same as the PR's? If there is only one commit, GitHub uses the commit's message. Otherwise, the PR's title gets used.

**Comment by bpatterson88** [comment]
In order to get the avatar sized in accordance with the Figma design, I extended the Tailwind spacing scale to include 11, which equals 2.75rem. That setting will be included by default in Tailwind v2.

**Comment by bpatterson88** [comment]
@jcfranco Any idea why Travis is failing? I rant the test suite locally and it passed. Also, added a few more commits to this branch -- let me know if anything needs renamed.

**Comment by jcfranco** [comment]
@bpatterson88 Not sure. Can you run the build again? It seemed to fail on the storybook/screener step:

```
Starting Storybook server...
> start-storybook --port 2000 --config-dir .storybook --static-dir ./__docs-temp__ --ci 
Please wait. Starting Storybook may take a minute...
Port not returned when starting Storybook server
---
Exiting Screener Storybook
Run with --debug flag to log additional information
Need help? Contact: help@saucelabs.com
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @esri/calcite-components@1.0.0-beta.55 test:storybook: `concurrently --raw "npm:util:build-docs && screener-storybook --conf screener.config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @esri/calcite-components@1.0.0-beta.55 test:storybook script.
```

**Comment by eriklharper** [comment]
That's funny, I noticed the build on my `407/calcite-time` branch failed at the same place even though there were no broken tests.  Not sure why the `npm run test:storybook` script returns this for both our branches:

```
Port not returned when starting Storybook server
```

And, if this has to do with why it exits with a 1.

**Comment by bpatterson88** [comment]
@jcfranco Same error after running the build again.

**Comment by eriklharper** [comment]
I sent an issue to our support contact at Screener.io to see if they have any additional error log content that can help us understand why that error is happening.

**Comment by jcfranco** [comment]
I think the issue is a broken link in the storybook. Submitted a PR for this: https://github.com/Esri/calcite-components/pull/2213.

**Review by bstifle — APPROVED** [review]
Looks good!!!

**Comment by eriklharper** [comment]
> I think the issue is a broken link in the storybook. Submitted a PR for this: #2213.

So the build passed after you fixed this broken storybook import?

**Comment by bpatterson88** [comment]
Yeah, #2213 fixed the failing test.

**Pull request merged**
