### PR TITLE
test(tooltip): updated tooltip demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2642 

## Summary
- updated tooltip demo page

### CODE REVIEW

**Comment by julio8a** [comment]
For this one, I'm assuming we'll use Screener's interactive tool to activate and take a screenshot of the tooltips @eriklharper?

**Comment by julio8a** [comment]
on the first column, the left shows up on the right
image

Leading shows up as trailing
image

@caripizza @jcfranco @bstifle do you guys think we need all these variations?

**Comment by bstifle** [comment]
@ManahariDahal 

lets make some layout adjustments!

image

1. labels on the left.
2. put buttons in columns like Alert does. the full width buttons are distracting
3. add vertical space between each row (56px?)

**Comment by ManahariDahal** [comment]
> on the first column, the left shows up on the right
> image
> 
> Leading shows up as trailing
> image
> 
> @caripizza @jcfranco @bstifle do you guys think we need all these variations?

Is it a problem with the component itself? I double-checked, and the placements have the correct name, but it's not showing up how it should.

**Comment by ManahariDahal** [comment]
> on the first column, the left shows up on the right
> image
> 
> Leading shows up as trailing
> image
> 
> @caripizza @jcfranco @bstifle do you guys think we need all these variations?

I was finally able to find what was wrong with the _left_ and _leading_. If the size of the tooltip is greater than the size of the remaining space, it will change its position accordingly. 
For instance, if there is a button on the left side of the window and there's not much space for the tooltip, it will reverse its position, same with the right side. Hope it makes sense.

**Comment by bstifle** [comment]
>do you guys think we need all these variations?

yes, definitely!

**Review by bstifle — APPROVED** [review]

**Review by julio8a — APPROVED** [review]
Nice!

**Comment by julio8a** [comment]
Might want to merge laster to see if we can get Travis to be nice.

**Pull request merged**
