### PR TITLE
test(avatar): updated calcite-avatar demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2526 

## Summary
- match the current calcite-avatar demo page according to the Figma design
- _small_, _medium_ and _large_ variants included

### CODE REVIEW

**Comment by bstifle** [comment]
@ManahariDahal we should get the ID color test back in the demo:

in light and dark themes... the theme changer wont quite work for this one, so we'll need to include both on default.
image
image


Also, can we get these in there?:
image


thanks man!

**Review by bstifle — APPROVED** [review]

**Comment by driskull** [comment]
@ManahariDahal for all these demo page updates, can you run the page through the aXe toolbar extension to ensure the HTML is valid and is passing accessibility standards?

https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

**Comment by julio8a** [comment]
@driskull, the priority for this round of demo pages is to get all the variations to the demo pages. We want to have something together for manual testing and automated testing. 

The a11y testing is important, but something we can get on the demo pages in the second round.

**Review by julio8a — APPROVED** [review]
Looks good!

**Pull request merged**
