### PR TITLE
test(slider): updated slider demo page

### PR DESCRIPTION
**Pull request by ManahariDahal**
**Related Issue:** #2638 

## Summary
- updated _calcite-slider_ demo page

### CODE REVIEW

**Review by bstifle — APPROVED** [review]
perfection 🏆

**Comment by julio8a** [comment]
We don't need the mirrored, we should remove these.

**Comment by jcfranco** [comment]
> We don't need the mirrored, we should remove these.

Will there be a replacement for this? `mirrored` is different from RTL and the existing set up helps catch regressions on  the different slider configurations + mirrored.

**Comment by julio8a** [comment]
Maybe I got confused with some that seem like duplicates, is there a difference between these two columns?
image

**Comment by jcfranco** [comment]
The 2nd column does not not look mirrored.

**Comment by julio8a** [comment]
Let's mirror the right column all the way through. @ManahariDahal

**Comment by ManahariDahal** [comment]
@jcfranco does it have to do with the histogram specifically? It's weird that it's not mirroring it. `mirrored` attribute is working for every other apart from the histogram.

**Comment by jcfranco** [comment]
> `mirrored` attribute is working for every other apart from the histogram.

I didn't notice that we were talking specifically about the histogram portion of the demo page. That is by design. `mirrored` will not kick in if there's a histogram involved. Sorry about the confusion.

**Comment by ManahariDahal** [comment]
> > `mirrored` attribute is working for every other apart from the histogram.
> 
> I didn't notice that we were talking specifically about the histogram portion of the demo page. That is by design. `mirrored` will not kick in if there's a histogram involved. Sorry about the confusion.

yeah, sorry for the confusion on my part too. I will remove the mirrored part in the histogram then.

**Review by julio8a — CHANGES_REQUESTED** [review]
Remove mirrored for histogram section

**Review by julio8a — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
