### PR TITLE
refactor(tree, tree-item): update scales, styles to match Figma

### PR DESCRIPTION
**Pull request by caripizza**
**Related Issue:** #2080, #2082, #2041, #2460

## Summary
Adds large scale to tree, and updates styles to match Figma. (WIP)

### CODE REVIEW

**Comment by julio8a** [comment]
This is looking nice!

Thoughts @bstifle

**Comment by bstifle** [comment]
@caripizza these are looking cool!!! since this one is thick... gonna really need to spend time documenting some things.

generally, the spacing is close. The ones with input-enabled need the most work. And from what i am seeing the "lines" create some staggering

I'll try and document all this by the end of the day

**Comment by caripizza** [comment]
> generally, the spacing is close. The ones with input-enabled need the most work. And from what i am seeing the "lines" create some staggering.

Makes sense

> also, none of the chevrons should be getting thicker or blue on hover/open/things selected within

Okay that's fine, I was just thinking it'd be nice to tell when a collapsed tree-item's children are selected.

**Comment by caripizza** [comment]
Closing this one, moving forward in pr #2803 for scales first. (#2082 will be implemented in a subsequent pr next sprint - as soon as I firm up the designs with @bstifle for each of the 5 selection-modes in Figma.)

**Pull request closed without merging**
