### PR TITLE
fix(action-bar): Better handling of overflow actions on smaller screens

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #3025

## Summary

fix(action-bar): Better handling of overflow actions on smaller screens #3042

## This PR

- Modifies the mutationObserver to listen to `subtree` changes.
- Calls resize on `connectedCallback`
- Checks resize for an actual height greater than 0 before continuing.
- Cleans up code for resizing based on the host element clientHeight.
- Cleans up code for a slot name.

### CODE REVIEW

**Comment by driskull** [comment]
@jcfranco can we maybe get this into the release for MV?

**Review by jcfranco — APPROVED** [review]
LGTM! Before merging, can you add a test for this? It's labeled as fix, but it has no repro case nor info on how to reproduce.

**Comment by driskull** [comment]
@jcfranco I'll change it to `feat` since it may not be a fix. However, the change is to start listening for sublist changes on the mutation observer. I'm not sure if we need a test for that part.

**Comment by jcfranco** [comment]
> However, the change is to start listening for sublist changes on the mutation observer. 

That's a change of behavior to me (feat) and would warrant a test.

**Review by jcfranco — APPROVED** [review]
Noice! 🎉 🌮 :t-rex:

**Pull request merged**
