### PR TITLE
build(tests): skip icon asset copying as these are stubbed

### PR DESCRIPTION
**Pull request by jcfranco**
Icon data fetching is stubbed, so copying assets shouldn't be necessary anymore.

### CODE REVIEW

**Comment by paulcpederson** [comment]
It seems a lot of the other tests rely on icons being there. Should we close this or do you want to look into it more, @jcfranco ?

**Comment by jcfranco** [comment]
Are the assets needed if the icon element is sized appropriately?

**Comment by paulcpederson** [comment]
Not sure I totally understand your q. I was just reading through the build log and see that multiple component tests now fail due to 404'ing on an icon request. Not copying over the assets I think causes these 404's. 

The icon request will happen for each size independently, so `banana16` is a different request than `banana24`, but I'm pretty sure I'm not really answering your question 😆

**Comment by jcfranco** [comment]
Sorry for not adding more info, my goal is to make test runs faster by skipping asset copying. I believe most if not all tests that query or interact for `calcite-icon` don't need the SVG path data that's used internally by the component.

**Comment by paulcpederson** [comment]
Yes, I think you're probably right, they just check if there is a string at all or that the icon element is there. Carry on, sorry to disturb 

giphy

**Comment by julio8a** [comment]
What's the status of this PR?

**Comment by jcfranco** [comment]
@julio8a Sorry for the delay. Still working on this. Stubbing fetch requests in E2E tests turned out a little tricker than I had expected.

**Comment by julio8a** [comment]
This one has been opened for some time now, is it still valid?

**Comment by jcfranco** [comment]
Still valid, but I'll close for now. I'll revisit later.

**Comment by julio8a** [comment]
Thanks @jcfranco

**Pull request closed without merging**
