### PR TITLE
fix(slider): add high contrast specific styles for component

### PR DESCRIPTION
**Pull request by mpriour**
Specifically:
* Adds a visible color for the track and the selected portion of the track
* Removes the boxes around the handles
* Makes the handles visible
* Makes the precise handle's handle extension visible

**Related Issue:** #4514

### CODE REVIEW

**Comment by mpriour** [comment]
Changes make the slider look like this in high contrast:

Screen Shot 2022-05-09 at 4 48 48 PM

**Review by macandcheese — APPROVED** [review]
Thank you @mpriour, looks great !

**Comment by mpriour** [comment]
@benelan The e2e tests that failing seem to be from the color picker. I did not change anything in that component's files.

**Comment by benelan** [comment]
I'll get that fixed for you @mpriour

**Comment by mpriour** [comment]
Thanks @benelan

**Pull request merged**
