### PR TITLE
fix(rating): add props for accessible labels, structure as radio button

### PR DESCRIPTION
**Pull request by paulcpederson**
## Summary

- Adds two additional props for configuring screen reader labels for the rating component. 
- Structures the rating like a radio-input group (left/right to change selection, etc)
- Updates styles to use tailwind

@macandcheese can you look at these styles and make sure it visually looks like it used to?

### CODE REVIEW

**Comment by macandcheese** [comment]
Good refactor, certainly a simpler component now... 

Few q's...

It's a little weird that when you "enter" a rating that has an average set, it doesn't act as if you are setting that rating. For example in the video, I tab into the rating, but I have to move to the second star to "set" a rating. I think MUI has an example of "pristine" rating where you can tab to focus the entirety of the rating group, and still manage to leave without affecting the value for an example like this. ( https://material-ui.com/components/rating/#simple-ratings "pristine" example). Since users no longer have to "enter or space" to accept, it's weird if a user wanted to rate as "1", since they'd need to move to 2, then back to 1 to select that.


main_large (1)
When tabbing backwards into the "default" with average" example, it focuses a different star than when focusing in:
main_large



Some style nitpicks (sorry):

- Read only "half filled" should be placed on top of a full grey star vs. empty one:

| This PR |  Master |
| --- | --- |
| Screen Shot 2020-11-11 at 12 15 29 PM|Screen Shot 2020-11-11 at 12 18 35 PM|

- The "half filled stars" here have yellow bg, vs. grey previously (maybe I like the version you added better visually though? I'm not sure there is enough of a difference in inferred meaning to change it back, lol. )

| This PR |  Master |
| --- | --- |
|Screen Shot 2020-11-11 at 12 16 09 PM |  Screen Shot 2020-11-11 at 12 18 51 PM |

- There's kind of a weird animation lag with the partial star on hover off: 
main_large (3)

**Review by macandcheese — APPROVED** [review]
Good update, thanks. Added some obnoxiously nitpicky feedback items.

**Comment by paulcpederson** [comment]
This is all good feedback, will try to get some updates in today

**Comment by paulcpederson** [comment]
@macandcheese ok, I think I got all the style stuff (thanks for catching)

I'm not sure on the `pristine` or focus in/out stuff. All of that behavior is just how radio buttons work. We could probably add as a later enhancement (especially if we add a "set on blur" type feature in the future)

**Comment by paulcpederson** [comment]
I think I'm going to merge this so it can make today's release. We can keep finessing the interactions in further prs

**Comment by bstifle** [comment]
agreed on the enter/space to confirm comment when arrowing through. would be dope to keep the starts yeller until doing that as noted as such

**Pull request merged**
