### PR TITLE
fix(card): provide more meaningful screen reader label for selectable cards (deprecates `deselect` message override)

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #5585

## Summary

Changes the text used for the card's checkbox to provide correct state information. Before, screen readers would read "Select, unchecked, checkbox"/ "Deselect, checked, checkbox". This text should now be more meaningful: "Selectable card, checked, checkbox"/ "Selectable card, unchecked, checkbox". 

## Notes

* The suggested fix from the audit included an identifier for the card and using the card's title/subtitle was considered, but not used as we can't reliably use it since neither are technically required.
* This reuses the `select` message and deprecates `deselect`. This is not considered a breaking change as any existing text overrides from `select` will still be used and provide applicable context and any provided `deselect` will end up being ignored.

### CODE REVIEW

**Comment by jcfranco** [comment]
@geospatialem Any ideas for automated testing here? Not sure if asserting on the rendered string is of value or not as this change is more about the interpretation of the text. LMK what you think.

**Review by driskull — APPROVED** [review]
👍 

Looks good.

We might want to check other places we use `aria-checked` and make sure they represent the item description and not the action.

**Comment by geospatialem** [comment]
> @geospatialem Any ideas for automated testing here? Not sure if asserting on the rendered string is of value or not as this change is more about the interpretation of the text. LMK what you think.

@jcfranco I don't think we could run automated testing in this case since it would have technically passed prior to this fix through automation.

**Comment by jcfranco** [comment]
> We might want to check other places we use aria-checked and make sure they represent the item description and not the action.

@geospatialem Do you think our a11y audit caught all of these?

**Comment by geospatialem** [comment]
> @geospatialem Do you think our a11y audit caught all of these?

It looks like there was only one other instance across components, which was in `stepper`/`stepper-item` with https://github.com/Esri/calcite-components/issues/5602. 

@jcfranco We have it slotted for the July release, but perhaps we could add it in the current one if its fix is similar?

**Comment by jcfranco** [comment]
> perhaps we could add it in the current one if its fix is similar?

Let's keep it where it is and we can move it to an earlier milestone if our backlog allows.

**Pull request merged**
