### PR TITLE
fix: Enter key event should submit form from form elements. (#3961)

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #3961

## Summary

fix: Enter key event should submit form from form elements. (#3961)

### CODE REVIEW

**Comment by driskull** [comment]
Opened this PR to get some eyes on it. 👀 

We would need to do some exclusionary stuff for components that have more than 1 element inside of them that would trigger an enter key and we wouldn't want it to submit the form.

WDYT @jcfranco ?

**Comment by jcfranco** [comment]
This is looking good! Do you have an example of how a component would implement `onEnterShouldSubmit`?

**Comment by driskull** [comment]
> This is looking good! Do you have an example of how a component would implement onEnterShouldSubmit?

Not yet. I'm still on the fence about this. I wonder if it might be easier if a component just called `formEl?.requestSubmit()` when it needed to?

The only benefit of having to opt out is that we enforce the enter key functionality.

**Comment by jcfranco** [comment]
Adding to your idea, how about adding a method to the interface for submitting? Another benefit to it is that it keeps all form-related behavior/details in the util. I like the idea of having the util take care of it, but managing complex components will be tricky.

**Pull request closed without merging**
