### PR TITLE
chore(icons): update icons to 3.16.5

### PR DESCRIPTION
**Pull request by julio8a**
## Summary

Update UI icons to the latest release.

### CODE REVIEW

**Comment by macandcheese** [comment]
Ah - looks like the latest on `npm` isn't up to date yet https://www.npmjs.com/package/@esri/calcite-ui-icons

**Comment by julio8a** [comment]
I'll publish

**Comment by julio8a** [comment]
I published on NPM, though not sure why Travis CI is failing.

**Comment by driskull** [comment]
Seems like the updated package lock is missing.

**Comment by jcfranco** [comment]
> I published on NPM, though not sure why Travis CI is failing.

You can get more info if you look at the build log: https://app.travis-ci.com/github/Esri/calcite-components/builds/232100819

> npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

Looks like the lock file is out of sync.

**Comment by julio8a** [comment]
All checks are good, can someone take a look at this again?

**Review by jcfranco — APPROVED** [review]
👍🏼

**Comment by jcfranco** [comment]
FYI: https://github.com/Esri/calcite-components/pull/2511/files bumps the icons to the same version, so I don't think it would cause a merge conflict.

**Comment by julio8a** [comment]
ah, if it's already there then I'll just close this one.

**Pull request closed without merging**
