### PR TITLE
feat(ListItem): updates flex definitions on start and end content slots

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #4336

## Summary
When no center content is rendered, `content-end` and `content-start` slots occupy the available space in the container.

@benelan Not sure if I added the correct Milestone or not.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
This looks good. Do we need any tests for this or is screener handling it?

**Comment by asangma** [comment]
@driskull I can add tests to check for the flex style on those divs.

**Comment by asangma** [comment]
@driskull Actually, I think screener would handle this, but I could use a hand setting up a couple screener tests for the updates.

**Comment by asangma** [comment]
@benelan Would you mind giving me a hand with that?

**Comment by benelan** [comment]
> @benelan Would you mind giving me a hand with that?

sure thing

**Comment by benelan** [comment]
@asangma, I added the new screener snapshot based on the demo you added. Can you please accept the changes, or let me know if I should make any additional changes.

**Comment by asangma** [comment]
Thanks @benelan! Will do.

**Comment by asangma** [comment]
@benelan Reviewed and updated.

**Pull request merged**
