### PR TITLE
fix(time-picker): high contrast visibility of outlines in focus and hover states

### PR DESCRIPTION
**Pull request by mpriour**
**Related Issue:** #6118 

## Summary
* ensures that outlines are fully visible in high contrast
* Adds a z-index to the buttons and inputs in hover or focus state
* Does not have any noticeable change in regular contrast mode

### CODE REVIEW

**Comment by mpriour** [comment]
@benelan & @geospatialem I'm not sure how I messed up the semantic PR but I know I did not do anything to the E2E tests that are preventing the checks from passing.

**Comment by geospatialem** [comment]
> I'm not sure how I messed up the semantic PR

@mpriour I'm not sure if this'll fix it, but might need to add the component to the fix. Something like:

```
fix(time-picker): high contrast visibility of outlines in focus and hover states
```

> did not do anything to the E2E tests that are preventing the checks from passing.

Will look into the e2e test failure, might just need to re-run them. 🏃🏻 But agreed, does not apply to this fix.

Going to take a peek at the fix now, thanks for taking a look @mpriour!

**Review by geospatialem — COMMENTED** [review]
Looking great! ✨ 

Noticed when using `input-date-picker` the first and last items outline extends a bit outside the component. Very minor, and the `date-picker` looks good by itself, but wanted to mention if its something we should address in this PR.

input-date-picker-high-contrast-audit

**Comment by mpriour** [comment]
@geospatialem It looks like I can remove the outline offset and shrink the focus ring in high-contrast mode to just be the size of the input.

Screen Shot 2022-12-20 at 10 40 14 AM

**Comment by mpriour** [comment]
@geospatialem Looks like all the pre-merge checks have passed. Take another look when you get a chance and verify that the focus ring doesn't overlap other parts of the UI in high contrast mode.

**Review by driskull — APPROVED** [review]
LGTM! 👍

**Comment by mpriour** [comment]
@benelan @driskull - All checks have passed and required code reviewers have reviewed code. Why can I not squash merge this PR at this time?

**Comment by benelan** [comment]
We have some unstable visual regression tests that were blocking merging. I just cleared those up, so its ready to install. Thanks for the contribution!

**Pull request merged**
