### PR TITLE
refactor(pagination)!: rename properties.

### PR DESCRIPTION
**Pull request by anveshmekala**
**Related Issue:** #6285 

BREAKING CHANGE: Rename properties.

- Removed the property `num`, use `pageSize` instead.
- Removed the property `total`, use `totalItems` instead.
- Removed the property `start`, use `startItem` instead.

### CODE REVIEW

**Comment by ashetland** [comment]
@SkyeSeitz we'll need to update prop names in Figma.

**Comment by SkyeSeitz** [comment]
> @SkyeSeitz we'll need to update prop names in Figma.

Thanks for the heads up on this, Aaron. I confirmed if any changes are needed in Figma. It looks like none of these would apply to the kit as Figma does not set `start` or `total` properties and every number is the same internal component with a shared text property that needs to stay generically called `number` 👍🏽

**Comment by ashetland** [comment]
> > @SkyeSeitz we'll need to update prop names in Figma.
> 
> Thanks for the heads up on this, Aaron. I confirmed if any changes are needed in Figma. It looks like none of these would apply to the kit as Figma does not set `start` or `total` properties and every number is the same internal component with a shared text property that needs to stay generically called `number` 👍🏽

Excellent news. Thanks @SkyeSeitz!

**Review by jcfranco — APPROVED** [review]
LGTM!

Can you make sure to use the prop names, instead the attributes, in the breaking change notes right before merging?

**Pull request merged**
