### PR TITLE
fix(progress): make progress visible in high contrast (#3986)

### PR DESCRIPTION
**Pull request by mpriour**
* Use system colors for background of track and bar elements

**Related Issue:** #3986 

## Summary
Provide system colors for track and bar of the progress component

Looks like this on high contrast in Edge on Windows:

Screen Shot 2022-01-23 at 8 03 22 PM

Uses `HighlightText` for the track, which should always be a light color on dark high contrast themes and `LinkText` for the bar which should always be a highly visible color and different from borders or text.

### CODE REVIEW

**Comment by mpriour** [comment]
@macandcheese do you approve of the design used here, or would you like to see something different?

**Review by macandcheese — APPROVED** [review]
Looks good to me - thanks @mpriour !

**Pull request merged**
