### PR TITLE
test(action): Remove emitting warning logs for value/pick lists.

### PR DESCRIPTION
**Pull request by driskull**
test(action): Remove emitting warning logs for value/pick lists.

### CODE REVIEW

**Comment by driskull** [comment]
@jcfranco can you review this?

**Review by jcfranco — COMMENTED** [review]
I don't think we should only emit when elements are connected. There could be use cases for the components to be used in a disconnected fashion. For comparison, native elements will dispatch events regardless. 

Is this fixing a specific issue or is it to mute the warning messages in test runs?

**Comment by driskull** [comment]
>  Is this fixing a specific issue or is it to mute the warning messages in test runs?

Its to mute warnings in test runs.

The value/pick list are emitting them in console.

```
PASS src/components/calcite-pick-list/calcite-pick-list.e2e.ts (60.589 s)
  ● Console
    console.warn
      STENCIL: The "calciteActionClick" event was emitted, but the dispatcher node is no longer connected to the dom. 
      Location: http://localhost:3333/build/index-0add6fca.js:2710:70
      at t (node_modules/@stencil/core/testing/index.js:3827:67)
      at node_modules/@stencil/core/testing/index.js:3828:5
      at node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
          at Array.map (<anonymous>)
      at Object.emit (node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
      at Page.emit (node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
      at Page._addConsoleMessage (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:757:14)
      at Page._onConsoleAPI (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:700:14)
```

**Comment by jcfranco** [comment]
I think https://github.com/Esri/calcite-components/blob/master/src/components/calcite-pick-list-item/calcite-pick-list-item.tsx#L247 needs to use the `calciteActionClick` instead of click.

**Pull request closed without merging**
