### PR TITLE
fix(radio-button): scale selection indicator with radio button size #3875

### PR DESCRIPTION
**Pull request by mpriour**
* Use `--calcite-radio-size` css variable to properly size and center the selection indicator on radio-button component

**Related Issue:** #3875

### CODE REVIEW

**Review by driskull — COMMENTED** [review]
This looks good to me, i'll let another chime in :)

**Comment by mpriour** [comment]
Previously:



With scaling fix:

**Comment by mpriour** [comment]
@driskull It doesn't look like anyone else wants to chime in. Would you mind giving this change approval?

**Review by jcfranco — APPROVED** [review]
Code LGTM! @macandcheese Can you review the visual changes?

**Pull request merged**
