### PR TITLE
fix(rating)!: display-value => show-chip, also works now

### PR DESCRIPTION
**Pull request by paulcpederson**
## Summary

We need the ability to hide the value of the count/average numbers. I went to add a prop for this and realized it was already there, we just weren't using it 🤦🏻 .

This updates the ratings component to pay attention to the existing `display-value` prop and adds tests, docs, jsdoc for it as well.

### CODE REVIEW

**Review by caripizza — COMMENTED** [review]
Nice! Only question I have is about the `displayValue` prop name - this new behavior makes me instead think of a name like `displayStats` (or `showChip` like Adam had mentioned in Teams), since it applies to either count or average props on the component and not the value prop. 🤔

**Comment by paulcpederson** [comment]
Yeah, I was going to call it `show-summary`, but then found this prop, we could definitely change the name as it was completely unused and undocumented 😂

**Comment by caripizza** [comment]
> Yeah, I was going to call it `show-summary`, but then found this prop, we could definitely change the name as it was completely unused and undocumented 😂

Perfect, can you rename to `show-chip`? 🐿️

**Comment by paulcpederson** [comment]
@caripizza updated

**Review by caripizza — APPROVED** [review]
lgtm 👍

**Pull request merged**
