### PR TITLE
refactor(combobox): single select text wrong font weight

### PR DESCRIPTION
**Pull request by justinhough**
**Related Issue:** #2901

## Summary

Filled weight in combobox single select text changed from `avenir-medium 500` to `avenir-regular 400`

### CODE REVIEW

**Comment by julio8a** [comment]
@Esri/calcite-components-reviewers 

Here's another instance where Screener should have failed as the font-weight changed. :(

**Comment by jcfranco** [comment]
It looks like the font-weight is already 400: https://esri.github.io/calcite-components/?path=/story/components-controls-combobox--single

Screen Shot 2021-09-15 at 9 54 48 AM

**Comment by justinhough** [comment]
@jcfranco That is odd. While I was working on this the computed font-weight was coming out as 500.

**Comment by macandcheese** [comment]
The combobox is inheriting font-weight:
https://jsbin.com/kozixanebe/1/edit?html,output

The combobox items themselves (in the dropdown) also are affected.

**Review by jcfranco — APPROVED** [review]
LGTM!

**Review by jcfranco — APPROVED** [review]
💥

**Pull request merged**
