### PR TITLE
chore!: ensure boolean attribute usage is spec-compliant

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

This updates all boolean attributes to conform to the [HTML5 spec](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes), namely:

> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

## Breaking changes

This exposed another issue with a few components that had reflected boolean props with a default of true. Users would never be able to disable the values with plain HTML + spec-compliant boolean attributes. 

The only way to set the attribute to false would be to programmatically set the prop or to use the non-standard `user-select="false"`.

The following breaking changes were made:

* `calcite-action-bar` + `calcite-action-pad`: dropped `expand` in favor of `expand-disabled`
* `calcite-date`: dropped `proximity-selection` in favor of `proximity-selection-disabled`
* `calcite-link`: removed `userSelect` since it is not used by the component
* `calcite-slider`: changed default of `snap` to false

† behavior is preserved when attr is omitted

**Note**: there is one remaining prop on `calcite-tree` (`root`), but I left it as is since it is internal.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍   Looks good. Thanks @jcfranco !

**Review by eriklharper — APPROVED** [review]

**Comment by jcfranco** [comment]
The last commit brings the total of impacted components to:

* `calcite-action-bar`
* `calcite-action-pad`
* `calcite-date`
* `calcite-link`
* `calcite-slider`

@paulcpederson could you review the `date` & `slider` changes?

**Comment by macandcheese** [comment]
Looks good! Only question would be regarding slider. I know you just matched what’s there now but should it be “enable-snap” where users opt into that functionality? To me having “enable-*” instead of “disable-*” for things that add functionality makes sense, but would be extra work to update for folks.

More of a “what’s expected out of the box” question than anything with the PR changes, but could address now.

**Review by macandcheese — APPROVED** [review]
Approved w question

**Comment by paulcpederson** [comment]
@jcfranco the date changes are going to be _sort of_ irrelevant with the "separate date from date input" stuff that @driskull is working on. 

As per slider, I think what we've been learning with a lot of these API changes is that:

1. default behavior should not require any props
2. opt-in props should be worded positively

So that would mean for slider we come up with a name that allows devs to opt-in to a slider with no default snapping. Maybe `continuous`? Either that or we decide that no snapping is the default behavior and we leave the `snap` prop.

**Comment by paulcpederson** [comment]
Actually looking through some of the history (like this: https://github.com/Esri/calcite-components/pull/703#discussion_r450512197) seems like `disable-X` is common and fine. We should probably add a section on prop naming to our conventions if it doesn't exist already

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
Approved pending build/conflict resolution

**Comment by jcfranco** [comment]
Thanks for reviewing!

@paulcpederson One last thing: going back to @macandcheese's question, are we good keeping snapping enabled by default?

**Comment by jcfranco** [comment]
Updated prop names based on our boolean prop naming conversation (https://github.com/Esri/calcite-components/issues/1145). Can you take a quick glance at the name changes (see description)?

**Review by driskull — CHANGES_REQUESTED** [review]
Looks like it's failing here: https://github.com/Esri/calcite-components/blob/3909ade6b0c3ae0166e3e6ea586cf3ab1a144ad2/src/components/calcite-slider/calcite-slider.tsx#L901

**Comment by jcfranco** [comment]
Fixed the missed rename. Thanks @driskull. Do the updated names look OK to you?

**Comment by driskull** [comment]
Names look good @jcfranco 🎉 . Moar breaking changes :)

**Pull request merged**
