### PR TITLE
feat(input): add inputmode property to specify mobile keyboard display

### PR DESCRIPTION
**Pull request by benelan**
**Related Issue:** #2949

## Summary
Added `inputmode` property to specify the mobile keyboard style
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

### CODE REVIEW

**Comment by jcfranco** [comment]
This PR is no longer needed because of https://github.com/Esri/calcite-components/pull/3396, right?

**Comment by benelan** [comment]
> This PR is no longer needed because of #3396, right?

This is a different prop (`inputMode`), but I'm going to make sure I get `enterKeyHint` working first before installing this one

**Comment by eriklharper** [comment]
Should we be creating non-standard attribute, in this case `input-mode` as opposed to `inputmode` or should we just pass the HTML standard attribute down to the native shadowed input with `inputMode={this.el.inputMode}` or if that's not accessible, then `inputMode={this.el.getAttribute("inputmode")}`?

**Comment by benelan** [comment]
@eriklharper I'm using the one from the base element, I tested and it worked for `enterKeyHint`

**Review by eriklharper — APPROVED** [review]

**Pull request merged**
