### PR TITLE
refactor(color)!: rename color to color-picker

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #1437 

## Summary

This renames the following components:

* `calcite-color` -> `calcite-color-picker`
* `calcite-color-hex-input` -> `calcite-color-picker-hex-input`†
* `calcite-color-swatch` -> `calcite-color-picker-swatch`†

† renamed to indicate that these are supporting components and not meant to be used standalone. Associated demo pages were dropped too and their readmes are no longer linked from the main story.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👀 Looks good to me. ❤️ 

💥

**Comment by driskull** [comment]
Looks like the failing test is unrelated. Maybe needs a `await page.waitForChanges();`

```
const date = await page.find("calcite-input-date-picker");
      49 | 
    > 50 |     await date.click();
```

**Comment by paulcpederson** [comment]
weird did that date test change recently? I feel like there is a ton of flakiness lately in the e2e tests...

**Comment by jcfranco** [comment]
@driskull Thanks! I'm working on a small PR for tests. I can fix it there.

**Comment by driskull** [comment]
I don't think it did but yeah they have been flakey. ❄️  👎

**Comment by julio8a** [comment]
Yas!

**Comment by jcfranco** [comment]
Forgot to rename the events. 🤣  PR coming up!

**Pull request merged**
