### PR TITLE
fix: Theme is no longer set by default.

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** N/A

## Summary

- Removes automatic setting of theme in some components.
  - This allows a user to set the theme attribute on an ancestor to switch the theme.
- Fix demo for color picker
- fix typing
- remove getElementTheme() utility function

### CODE REVIEW

**Review by jcfranco — COMMENTED** [review]
Thanks for fixing the color picker stuff I missed! 😅 

So, does this mean components won't have a theme default at all?

**Comment by driskull** [comment]
> So, does this mean components won't have a theme default at all?

Yes, I think so. I think I got all of them.

**Review by jcfranco — APPROVED** [review]
👍 

Do you know if we have any doc or samples showing the new way to work w/ theme?

**Comment by driskull** [comment]
> Do you know if we have any doc or samples showing the new way to work w/ theme?

@jcfranco nothing changes from previously, these components shouldn't be setting a default for theme. That way they inherit the css variables from any parent. Otherwise, it becomes more complex to switch themes.

**Comment by jcfranco** [comment]
> That way they inherit the css variables from any parent. 

So, only parents set the default theme or is it still up to the user?

**Comment by driskull** [comment]
Its up to the user where to set the theme

**Comment by jcfranco** [comment]
OK, so it is possible for the user to not set a default at all then. I guess I'm trying to figure out if the theme is still light by default even if the user does not set anything.

**Comment by driskull** [comment]
> theme is still light by default even if the user does not set anything.

Yes, that's how our CSS variables are set up.

**Comment by jcfranco** [comment]
Got it, thanks! 😄  I'm guessing  somewhere in the doc we'll have something about the default theme.

**Comment by paulcpederson** [comment]
I think we'll need to remove styles that directly hook into a theme attribute as well, as that will no longer happen. A quick search reveals the following:

```
src/components/calcite-alert/calcite-alert.scss:
  7  // dark theme
  8: :host([theme="dark"]) {
  9    --calcite-alert-dismiss-progress-background: #{rgba($blk-200, 0.8)};

src/components/calcite-button/calcite-button.scss:
  11  // dark theme
  12: :host([theme="dark"]) {
  13    --calcite-button-transparent-hover: rgba(255, 255, 255, 0.05);

src/components/calcite-chip/calcite-chip.scss:
    9  // dark theme
   10: :host([theme="dark"]) {
   11    --calcite-chip-transparent-hover: rgba(255, 255, 255, 0.05);

  173    // handle dark theme text accessibility for solid
  174:   :host([theme="dark"][color="#{$name}"][appearance="solid"]:not([color="grey"])),
  175:   :host([theme="dark"][color="#{$name}"][appearance="solid"]:not([color="grey"])) button {
  176      color: var(--calcite-ui-background);

  187  
  188:   :host([theme="dark"][color="#{$name}"][appearance="clear"]) {
  189      border-color: $bgColorClearAppearanceDark;

src/components/calcite-inline-editable/calcite-inline-editable.scss:
  66  :host(:not([editing-enabled])) {
  67:   &:not([theme="dark"]) {
  68      &::slotted(*) {

src/components/calcite-input-message/calcite-input-message.scss:
  20  
  21: :host([theme="dark"]) {
  22    --calcite-input-message-floating-background: #{rgba($ui-foreground-1-dark, 0.96)};

src/components/calcite-link/calcite-link.scss:
  8  // dark theme
  9: :host([theme="dark"]) {
  10    --calcite-link-blue-underline: #{rgba($d-bb-420, 0.4)};

src/components/calcite-scrim/calcite-scrim.scss:
  8  // dark theme
  9: :host([theme="dark"]) {
  10    --calcite-scrim-background: #{rgba($blk-240, 0.75)};
```

These vars will need to be moved to the actual global theme variables, I think.

**Comment by paulcpederson** [comment]
The colors in the above look largely made up, so would be good to standardize those anyways...

**Comment by driskull** [comment]
Should we do that as a follow up issue or in this PR?

I'm just trying to make it easier to switch from light/dark without having to do so by applying a prop on every component.

**Comment by paulcpederson** [comment]
follow up is probably fine

**Comment by driskull** [comment]
Created issue https://github.com/Esri/calcite-components/issues/1737

**Comment by driskull** [comment]
The doc already had the following...

```md
## Light Theme/Dark Theme

All components should allow developers to supply a `theme` property. This theme should _not_ have default value set:
```

We were just violating it already :P

**Review by eriklharper — APPROVED** [review]
This is a great idea, and thanks for clearing up those questions that I also had that Franco and Paul brought up :)

**Comment by driskull** [comment]
pick-list and value-list didn't even have a theme prop. I think all components should right??

Maybe we need a test built in to make sure all components have a theme prop and its not set to anything? @jcfranco is that possible?

**Pull request merged**
