### PR TITLE
build(deps): bump versions

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

Bumps dependencies, including Stencil: https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-240-2021-01-28

cc @eriklharper 

**Note**: the latest version of Stencil shows warnings when props are modified internally without being marked `mutable`. I fixed the ones that affected tests, but I'll need help fixing the rest.

### CODE REVIEW

**Comment by julio8a** [comment]
@paulcpederson is doing a release of calcite-colors (6.0.0) today. We should update that one too since there are some big (breaking) changes there.

**Review by driskull — APPROVED** [review]
👍 Nice

**Comment by paulcpederson** [comment]
@jcfranco @esri/calcite-colors v6.0.0 is out now

**Comment by jcfranco** [comment]
I'll submit a different PR for the @esri/calcite-colors bump.

**Comment by jcfranco** [comment]
☝️  https://github.com/Esri/calcite-components/pull/1491/

**Comment by eriklharper** [comment]
@jcfranco it looks like this update doesn't just warn you against mutating immutable properties, it blocks you from committing them entirely.   Is that intentional?

**Comment by jcfranco** [comment]
@eriklharper I suspect something else is causing that. https://github.com/ionic-team/stencil/commit/9c18fa0da217be0bd9e28672f2a0b3c9599de2db indicates that it only warns. We can look into it more if you have an isolated test case.

**Pull request merged**
