### PR TITLE
fix(button)!: Remove floating property from calcite-button

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #1167

## Summary

fix(button)!: Remove floating property from calcite-button in favor of clcite-fab component.  #1167

### CODE REVIEW

**Comment by driskull** [comment]
@asangma can you review the changes to the FAB shadow and adjust as necessary?

**Comment by noahmulfinger** [comment]
Randomly saw this PR so I wanted to clarify: This isn't removing the `loading` property right? Just `floating`? Because we're extensively using `loading` on calcite button currently.

**Review by macandcheese — APPROVED** [review]
Looks good, let's leave the shadow as is on fab - so correct as it is now. 

I do think we should change the title from loading -> floating as to not scare a bunch of folks 😉 

Thanks for getting this in!

**Comment by driskull** [comment]
Whoops. yes. wrong property

**Comment by driskull** [comment]
I think i'll need to modify the commit to fix that. Maybe better to just start a new PR?

**Comment by driskull** [comment]
fixed it I think.

**Comment by asangma** [comment]
👀

**Review by asangma — APPROVED** [review]
So kleen. 🧹

**Pull request merged**
