### PR TITLE
Improve tab-tile focus style

### PR DESCRIPTION
**Pull request by ffaubry**

### CODE REVIEW

**Comment by macandcheese** [comment]
I think this causes issues because tab titles are then not truly flush-left, in the screenshot there is a slight indent above the text immediately beneath, thoughts @bstifle - maybe we could use the "outset" version of focus here instead?

**Comment by bstifle** [comment]
Tabs focus look great nice work

**Comment by bstifle** [comment]
Outset focus, instead of padding makes more sense per @macandcheese

**Comment by ffaubry** [comment]
Thx guys. I will update and resubmit for review!

**Comment by ffaubry** [comment]
@bstifle @macandcheese Not sure I'm using the right thing here. 
This is what I'm getting:
image

**Comment by bstifle** [comment]
yeah that's weird. Z index?

**Comment by macandcheese** [comment]
Issue with overflow, because we want the tabs to scroll horizontally overflow: visible won't work in conjunction with letting it scroll in that direction. Like Bryan mentioned setting the z-index of the tab nav one higher than the tab content with the border works as intended:

Screen Shot 2020-07-10 at 9 02 35 AM
Screen Shot 2020-07-10 at 9 02 19 AM

But the horizontal scrolling needs to be solved for that example

**Comment by macandcheese** [comment]
@ffaubry @Esri/calcite-components - pushed an update to make this work. Not my proudest moment, but, it works for the desired design.

**Comment by paulcpederson** [comment]
nice, the old padding + negative margin trick.  Works for me!

**Comment by ffaubry** [comment]
Thx @macandcheese @bstifle I would have never got there.
Not my proudest moment neither.
Thx @paulcpederson as well.

**Pull request merged**
