### PR TITLE
feat(shell-panel): Place Action Bar in correct location when used in top / bottom Shell slots

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #6447

## Summary

- Adds CSS variables to the shell-panel.

``` 
--calcite-shell-panel-height: The height of the component.
--calcite-shell-panel-max-height: The maximum height of the component.
--calcite-shell-panel-min-height: The minimum height of the component.
 ```

- Adds `layout` property to the shell-panel.
- Sets slotted action-bars `layout` property to match its shell-panel `layout` property so that action-bars will appear horizontally when ideal.
- Adds resizing of shell-panels placed in "panel-top" and "panel-bottom" slots. (Mouse and keyboard)
- Adds story
- Adds demo
- Tests

### CODE REVIEW

**Comment by driskull** [comment]
@macandcheese I think I've taken this as far as I can. It just needs some styling and the min/max heights for horizontal panels assigned. Possibly any sizes for detached horizontal panels if that's allowed.

**Comment by macandcheese** [comment]
This is looking awesome @driskull - will give a final look and make any styling updates if needed.

**Comment by driskull** [comment]
Hey @macandcheese whats the status on this one? Do we want to try for release?

**Comment by macandcheese** [comment]
Yep, will update the default heights for the css variables, I think we can address having defined height scales separately - the css variables will let folks achieve needed height in mean time.

**Review by macandcheese — APPROVED** [review]
Looking great @driskull

**Pull request merged**
