### PR TITLE
docs(calcite-tile-select): adding instructions for listening to change events

### PR DESCRIPTION
**Pull request by eriklharper**
**Related Issue:** #1113

### CODE REVIEW

**Comment by jcfranco** [comment]
I don't think we want to do this based on a previous discussion. If I recall correctly, we had decided to not expose the internal events and instead provide component-specific events.

**Comment by eriklharper** [comment]
> I don't think we want to do this based on a previous discussion. If I recall correctly, we had decided to not expose the internal events and instead provide component-specific events.

I recall this discussion as well.  Do you know if an issue has been created to add those component-specific events?  I searched and couldn't find one.

**Comment by jcfranco** [comment]
I couldn't find anything either, so I'm guessing we need one. Can you create an issue for this?

**Comment by eriklharper** [comment]
Will do 👍

**Comment by jcfranco** [comment]
Thanks! 🙇🏼‍♂️

**Pull request closed without merging**
