### PR TITLE
feat(input-date-picker): add focus trap support

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #6668 

## Summary

Adds focus-trap to date-picker dialog to improve a11y.

**Note:** This also adds a util to help retrieve props from the currently focused element.

## Notable `focusTrapComponent` changes

* `connectFocusTrap` now supports passing a different focus-trap target element (for setting the focus trap on a component's subtree) and overrides to certain options from `focus-trap`'s `focusTrap()`.
* `activateFocusTrap`/`deactivateFocusTrap` now allow passing options to `focus-trap`'s `activate`/`deactivate` methods.
* `updateFocusTrapElements` is now optional.

### CODE REVIEW

**Comment by jcfranco** [comment]
FYI, this is based on https://github.com/Esri/calcite-components/pull/6805. [These](https://github.com/Esri/calcite-components/pull/6816/files/1642a84c5ec7ba2aaf881124ab0c4f6645f91011..d9b5becb56e67e744eba14f102e13ea1087bd66b) are the relevant changes for review.

**Comment by jcfranco** [comment]
+@geospatialem for a11y testing.

**Review by driskull — APPROVED** [review]
FocusTrap related changes look good!

**Review by geospatialem — COMMENTED** [review]
Likely out of scope for the focus trap support, and also *nitpick*:

Would we want to support keyboard focus where the "previous month" button is focused on first? 

Could see this being confusing for mouse users, too, but it seems like an odd behavior for AT to have to tab in after the dialog is displayed. Also makes it harder for AT users to close the dialog, as they would need to tab in first, then press `esc`.

**Comment by jcfranco** [comment]
@geospatialem I updated it so that when the date-picker is opened via the ⬇ key, it gets focused. Clicking won't move focus to allow users to type the value if desired.

**Pull request merged**
